### ISSUE TITLE
[Feature request] Mouse wheel to control volume bar (on hover)

### ISSUE THREAD

**Issue by Informatic** [jaedb/Iris#100]
It's be nice if:
 * [ ] Mouse wheel changed volume bar when it is focused (like it works in Windows 10/Ubuntu/KDE volume widget)
 * [x] Toggle mute when volume ("speaker") button is pressed

I'll try looking into implementing it later this week.

**Comment by Informatic** [comment]
Actually, it looks like mute is implemented but not working, as it throws: TypeError: _this2.props.mopidyActions.toggleMute is not a function

**Comment by jaedb** [comment]
The way the scroll currently works does not incorporate the `<input />` element. This means it will not respond to mouse scrolling during a hover event. This was looked at in early build, but as with most form elements, styling was severely limited and inhibited the UI of Iris. As such it was dropped in favor of plain HTML elements.

To achieve scroll-wheel interaction we would need to use a 3rd-party plugin to listen for mousewheel events.

Your other valid point about mute not working has since been resolved and included in the next release. Thanks for spotting this one as it's flown under the radar for some 2-3 major releases.

**Comment by Informatic** [comment]
Is there any particular reason you can't use onwheel? Only browser that lacks support for that is Safari, as far as I can tell after a short google.
