### ISSUE TITLE
Not clicking on mobile devices

### ISSUE THREAD

**Issue by Hugomm** [jaedb/Iris#109]
This extension for mopidy is great but I found what I think its an issue.

On song lists when clicking on a song from a computer it plays the song.
But on mobile devices when clicking on a song it does nothing. To play one song you have to select it, and then press options and play.

Can this be changed? 

Thanks in advance.

**Comment by jaedb** [comment]
On non-touch devices, single click selects a track and double-click plays the track. On touch devices you need to enter `edit_mode` (see #75) by tapping and holding on a track. Once in this mode you can select tracks and perform operations, like playing a track.

This may feel a little cumbersome to play a single track, however it's the more robust solution to handling bigger touch-device issues.

**Comment by Hugomm** [comment]
Yeah I understand how it works but I didnt found it really comfortable.

How about one play button on each song to play that song?

**Comment by jaedb** [comment]
It's been decided to update the functionality to be a little more like native mobile applications. This means instead of tap-and-hold to enter `edit_mode`, you can tap the checkbox zone (on small screens) to toggle a track's selected state.

When any tracks in a list of tracks (_TrackList_) are selected, a blue button is shown (_ContextMenuTrigger_) which is where you can interact with your selection.

Unfortunately there simply is not the screen real estate to have a play button on every track.
