### ISSUE TITLE
[Feature request] Control Icecast audio streaming service

### ISSUE THREAD

**Issue by jaedb** [jaedb/Iris#13]
_From @svallory on August 23, 2016 23:59_

Hey, guys! Thanks for the grate work!

What you guys think about integrating a stream player? I configured my mopidy to stream music using icecast. It would be really nice to be able to control the stream on spotmop.

What I'm thinking is that we could add a simple **hidden** stream player that would be controlled with the same controls if "listen here" is enabled. The only difference being that the volume would only mute the stream while play/pause would work as they do now.

This way we can have multiple people listening to the same mopidy stream. 

_Copied from original issue: jaedb/spotmop#129_

**Comment by jaedb** [comment]
Glad you're enjoying using Spotmop.

My initial response is that this is well beyond scope of the project, however I think all ideas should be given a fair opportunity :-)

Can you please provide me with the steps required to replicate your environment? Is the main objective of this to facilitate other devices to play the Mopidy server's audio stream (ie multi-room setup)?

**Comment by svallory** [comment]
Hey, I'm travelling and left my raspberry pi at home. But it was pretty straight forward. I just followed the instructions for mopidy and icescast. What I was tying to achieve is to allow people in different places (or rooms) to collectively listen and control the music they are listening to.

I didn't thought it was much beyond the scope because you already have the listen here capability. The change I propose is allowing many places to "listen here" simultaneously while mute wouldn't mute the stream for all but only local output.

**Comment by noobadmin** [comment]
Great idea! However, I was thinking it might be even nicer to have an option to add custom plugins for stuff like this. I'm having a multiroom audio setup with 4 rpi's using shairport-sync, while having mopidy running on my macbook (I'm using Iris simply because I hate spotify's UI - srsly that thing is crazy wrong) with audio output going into virtual device which I'm sending to shairports through third app. If there was an easy option to add custom code that would load ideally bellow the left side menu then all of was would be able to make a solution suiting each's individual needs while not having to hack your perfect core and struggle with each update :)

**Comment by jaedb** [comment]
As discussed in #179 to include every Mopidy extension's interface into Iris will make it extremely challenging for one guy (me!) to maintain as each extension evolves and changes with time. 

Therefore I believe energy is best spent making Iris do what it's designed for really well, rather than doing everything averagely. Jack of all trades, master of none, etc.
