### ISSUE TITLE
[Feature Request] increase/decrease volume with arrow keys when volume bar is active

### ISSUE THREAD

**Issue by zb2oby** [jaedb/Iris#130]
hello,

All in the title

is it possible ?

**Comment by jaedb** [comment]
Technically, yes. Using shortcut keys without modifiers (eg Ctrl) is a major pet peeve of mine and I find it confuses the UX. Also the arrow keys are otherwise used for scrolling down the page.

To remedy this, I had created shortcut keys for this very functionality. Please read [keyboard shortcuts](https://github.com/jaedb/iris/wiki/Features#keyboard-shortcuts)

**Comment by zb2oby** [comment]
Ok thank you
I still have an issue.
I cannot use all of them. i think it's a probleme with AZERTY keyboards (French version)

For me : 
**space**   is ok
**delete**   is ok
**ctrl + /**   is ok
**ctrl + >**   means    **ctrl + ;**
**ctrl + <**   means    **ctrl + ,**
**ctrl + ;**   means   **ctrl + $**
**ctrl + '**   means... nothing. i'm searching for an hour trying all kind of combinations... no way...

**Comment by jaedb** [comment]
I wonder if we change the shortcuts to use arrow keys (plus the `ctrl` key modifier). Do you think this would solve the issue for international keyboards?

So volume control would become something like `ctrl` + `up` and `ctrl` + `down`.

**Comment by zb2oby** [comment]
I think it could be a great idea. I guess Ctrl and arrows are always at the same places on most keyboards so it should be OK.
