### ISSUE TITLE
[Feature Request] Themes

### ISSUE THREAD

**Issue by DaEkstrim** [jaedb/Iris#148]
I'm not sure if this feature is already in place, but I'm wondering whether there is a way to create or alter the current theme. Personally I find the current one is too 'light' and prefer dark versions. Also when using the interface through a mobile, a darker interface will consume less power than a light one, thus increasing battery charge duration.

If I can do this by myself, a point to some instructions such as which SCSS files to change, would be appreciated.

**Comment by jaedb** [comment]
Great effort goes in to the UI, and a dark style has been explored on multiple occasions. You're welcome to tinker with the UI yourself, but it's not something that I'm looking to support in the near future. It would ultimately double the maintenance of styles and design elements, and as this is my 'in my spare time' project, time is precious. You're welcome to make a donation!

Regarding battery saving on darker interfaces, I would suggest reading up about how this works. In order to achieve any noticeable savings you would need to use pure blacks (eg `#000000`).

You can find all you should need to get started in the wiki, namely [Developing](https://github.com/jaedb/Iris/wiki/Advanced#setting-up-your-development-environment).

**Comment by DaEkstrim** [comment]
Thank you for getting back to me @jaedb, and thank you for the article pointer. I will take a look at it, and gauge if I'm capable to contribute such a feature. If I'm not mistaken, I did donate some months ago, but I'll check and act if it's not the case.

With regards to the battery vs darker interfaces subject, it must a type of screen (such as AMOLED) to benefit from the reduced battery consumption, since each pixel LED's brightness is controlled by reducing or increasing the voltage for that particular LED.

As a final note, I wish to thank you for dedicating your time in creating this project. You really did a splendid job.

**Comment by rvolosatovs** [comment]
It would be cool, if the colors would be configurable through the Web UI or mopidy config file. For starters, maybe at least allow defining the colors themselves https://github.com/jaedb/Iris/blob/master/src/scss/global/_variables.scss#L2-L17 ?

Does something like [this](https://github.com/rvolosatovs/Iris/commit/bd2d3da2b4286d2d87b29648112dbd1502e96480) makes sense? Then those variables could be configurable. The colors could probably be generalized to avoid having a variable for color of each element. Maybe in the same fashion as https://github.com/chriskempson/base16/blob/master/styling.md ?

I don't have too much front-end and styling knowledge... Essentially what I want to do is to be able to configure the interface to use the same colors as everywhere else in my environment (https://github.com/rvolosatovs/dotfiles/blob/master/Xresources#L4-L50) or at least be able to make the interface dark

**Comment by jaedb** [comment]
To customise the interface you'll need to be familiar with SASS, ReactJS. As a side-note, the latest interface has infact gone to the dark side. It's been a while in the making but it's finally been decided that dark complements the components of Iris better.

**Comment by DaEkstrim** [comment]
@jaedb Just popping by to let you know that I'm loving the new dark UI. Very well done.
