### ISSUE TITLE
[Feature request] Allow playlists to be shown in Spotify order

### ISSUE THREAD

**Issue by wezzynl** [jaedb/Iris#163]
I add a lot of playlists (I use the playlist == album idea), newer playlists get added to the top. That way I know what I still need to listen when I open Spotify and move playlists down the list later on.

When opening Playlists in Iris they sort on name and have some options for sorting. It would be nice if you could show them in the order they appear in Spotify. That way I don't need to open Spotify to see what the name of the album was that I had added late last night :)

**Comment by jaedb** [comment]
Unfortunately the Spotify sorting method isn't exposed in the Spotify HTTP API. 

Because _Your Playlists_ is a compilation of playlists from Mopidy (eg _Mopidy-Spotify_, _Mopidy-M3U_, etc) and the Spotify HTTP API (when you've authorized Iris), any load order would be unpredictable and would vary depending on which providers respond fastest.

Until the sort method is available in the API (eg `last_updated`), we can't reliably achieve this.

**Comment by Asheboy** [comment]
@jaedb What's your thoughts on sorting Spotify playlists in general? It would be possible to implement sorting by name, artist, album, duration and date added. From a UI perspective, I'd have thought that clicking on the column names to be pretty standard.
