### ISSUE TITLE
[Feature request] Save the country in config file

### ISSUE THREAD

**Issue by hcoohb** [jaedb/Iris#19]
Hi,

I am not entirely sure if the country code is actually used extensively, but after every upgrade it default back to NZ/en_NZ, and we have to change it back manually.
Is it possible to have that otpion as part of the extension settings in the mopidy config file?

As usual, thank you for your great work!
Cheers,
Fabien

**Comment by jaedb** [comment]
The country code is used when requesting region-specific content (eg New Releases) as well as checking availability of music in your region.

To me, the more pressing concern is more that it resets your value during upgrades. Do you find that any other settings are also reset after upgrading (ie Spotify Authentication)?

**Comment by tuxruffian** [comment]
@hcoohb You can do this already by adding a directive to the Spotify section of your `mopidy.conf` file. 
Example:

```
[spotify]
toplist_countries = US
```

**Comment by jaedb** [comment]
Please note that this is not configuration value is not respected by Iris. This is because we fetch from Spotify using their HTTP API, rather than the backend provided by _Mopidy-Spotify_.

I would like to piggy-back this configuration value as it doesn't make sense to have to configure Iris with the same values. This is planned for the next major release.
