### ISSUE TITLE
Top tracks not showing up.

### ISSUE THREAD

**Issue by Hugomm** [jaedb/Iris#191]
Im on 3.3.3 version and on an Artist page there is no track under Top Tracks. Tested on Incognito mode and the same. Is anyone having this issue?

![image](https://user-images.githubusercontent.com/14215939/29998658-5b47f22e-9031-11e7-9417-12bdc61bfb93.png)

**Comment by jaedb** [comment]
@Hugomm please raise issues using the proper issue template. This ensures I have all the information necessary to replicate and resolve the issue quickly.

Is this isolated to any particular artists? Are other artist elements coming through normally?

**Comment by Hugomm** [comment]
Sorry for no respecting the template @jaedb.

It's happening in every artist I click on.
Other elements such as Albums are showing up normally.

Thanks.

**Comment by hcoohb** [comment]
I also experienced this issue.
I found that during the update the country and language settings got reverted to NZ/ en_NZ.
When I switched them back to the country of my spotify account (AU/en_AU) the top tracks would now show correctly

**Comment by odiroot** [comment]
Same here although changing the country doesn't help. 

Checked different configurations lower case / upper case / Germany / US / Australia. Still empty.

**Comment by fekete-robert** [comment]
I've experienced the same problem since ~ upgrading to 3.2

**Comment by hcoohb** [comment]
I don't think it should be any country, it should be the country, language of your spotify account. germany would be DE / de_DE
Have you tried logging out of spotify and re-authenticate after  the change? Still no go?

**Comment by odiroot** [comment]
Thank you. Switching to my country actually worked. Interesting that Spotify API just doesn't return anything if you specify some other country instead of throwing an error.

So once again the country setting in Iris has to be the same as in Spotify account -- I guess it's tied to payment details country.

**Comment by jaedb** [comment]
The official country codes conform to [ISO 3166-1](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2). To avoid confusion this field could be a dropdown, rather than a free text input.

_Locale_ is in the format `aa_BB` where `aa` is [ISO 639](https://en.wikipedia.org/wiki/ISO_639) and `BB` is the country code as above. 

This information can all be found in the [Spotify API Documentation](https://developer.spotify.com/web-api/get-list-featured-playlists/). This is a link to an endpoint that uses both _country_ and _locale_ for explanation.

**Comment by jaedb** [comment]
I've added descriptions to each field in _Settings_, and introduced more detail when the API returns with errors. This should sort this as best we can for now.
