### ISSUE TITLE
Add search option to sort ordered by source

### ISSUE THREAD

**Issue by ugrug** [jaedb/Iris#198]
## Expected behavior
In search it should be nice to able to set the order of sources
E.g. spotify results shown 1st, tunein shown 2nd, youtube 3rd, soundcloud 4th etc.

## Actual behavior
Spotify track shown at the end of the list

## Steps to replicate
1. Start a search
2.

#### Operating systems affected
- [X] Windows:
- [ ] Mac: 
- [ ] Linux: 
- [ ] iOS: 
- [ ] Andriod:
- [ ] Other:

#### Browsers affected
- [X] Chrome: 
- [ ] Firefox: 
- [ ] Internet Explorer:
- [ ] Opera: 
- [ ] Other:

#### Screen sizes affected
- [X] Huge (ie desktop)
- [ ] Large (ie laptop)
- [ ] Medium (ie slim laptop/tablet)
- [ ] Small (phone)

## Before you submit
- [X] Yes, I have tested this issue thoroughly
- [X] Yes, I have attached screenshots and/or screencast of the issue in action
- [ ] Yes, I have included any relevant debug data and error logs

![image](https://user-images.githubusercontent.com/5822419/30264061-8eb2328a-96d7-11e7-9f7c-2ddc05bb1c1f.png)

![image](https://user-images.githubusercontent.com/5822419/30263794-a94f868e-96d6-11e7-8c5d-5855faa6bce9.png)

**Comment by antons-** [comment]
It would be good if this is looked at.

We primarily use the Spotify backend. We've recently added the Soundcloud and Youtube backends for the odd track but these results go right to the top above Spotify when searching, which is a pain. Most of my users don't realise they can click on the Sources button to turn these sources off..

Just a thought - what if we could turn off specific search sources in the config file and Iris uses that as defaults? If this was built, we would just enable the Spotify search source, and anyone that wants to use a different search source can just turn it on. We tend to use mpd to add tracks for Soundcloud/Youtube anyway since they are slow.

**Comment by jaedb** [comment]
This is in progress, and is likely to be bundled up with revisiting track selection and sorting. I'm looking to employ [SortableJS](https://github.com/RubaXa/Sortable) to handle all sorting functionality for better cross-device functionality.

**Comment by jaedb** [comment]
Resolved at d16729880d73d161aeafe6160c4cec6da334cb22
