### ISSUE TITLE
No option to play all tracks

### ISSUE THREAD

**Issue by winterscar** [jaedb/Iris#202]
## Expected behavior
I would like to start playing "My Tracks" as this is how I usually play my music. 
## Actual behavior
There is no play button on the "My tracks" page, and tracks can only be added manually. 

## Steps to replicate
1. Select the "Tracks" page in the sidebar
2. ???

#### Operating systems affected
- [x ] Windows:
- [ ] Mac: 
- [ ] Linux: 
- [ ] iOS: 
- [ x] Andriod:
- [ ] Other:

#### Browsers affected
- [ x] Chrome: 
- [ ] Firefox: 
- [ ] Internet Explorer:
- [ ] Opera: 
- [ ] Other:

#### Screen sizes affected
- [x ] Huge (ie desktop)
- [ x] Large (ie laptop)
- [ ] Medium (ie slim laptop/tablet)
- [ x] Small (phone)

## Before you submit
- [x ] Yes, I have tested this issue thoroughly
- [ ] Yes, I have attached screenshots and/or screencast of the issue in action
- [ ] Yes, I have included any relevant debug data and error logs

**Comment by jaedb** [comment]
I don't see this being viable on the basis that it will be an extraordinarily large request. One that will almost invariably hit the Spotify API limits.

_My Music > Tracks_ displays all tracks that are in your Spotify library. This includes not only individual tracks, but every track from every album that is also in your library. This makes it a very large list.

Personally I add playlists and artists to my library rather than individual tracks and albums, and even then I have over 1,000 tracks in _My Music > Tracks_. Trying to fetch all of these and play them is almost guaranteed to lock up the Mopidy server. There are ways around this, but I question the sensibility of playing the entire track library.

Instead I recommend selecting the tracks you want to play, and using the other tools available (`enter` shortcut key, right-click context menu, etc).
