### ISSUE TITLE
Tapping or clicking on a song should play it

### ISSUE THREAD

**Issue by winterscar** [jaedb/Iris#203]
## Expected behavior
When browsing music, tapping or clicking on a song should start playing it. Even better, the tap option should be configurable in settings to add it to the queue, play it next or play it now. 

This is most important on mobile
## Actual behavior
Tapping or clicking on a track does nothing. To play a track, the user must select the track with the radio button, and then use the overflow menu to play it. 
## Steps to replicate
1. 
2.

#### Operating systems affected
- [ ] Windows:
- [ ] Mac: 
- [ ] Linux: 
- [ ] iOS: 
- [ ] Andriod:
- [ ] Other:

#### Browsers affected
- [ x] Chrome: 
- [ ] Firefox: 
- [ ] Internet Explorer:
- [ ] Opera: 
- [ ] Other:

#### Screen sizes affected
- [x ] Huge (ie desktop)
- [x ] Large (ie laptop)
- [ ] Medium (ie slim laptop/tablet)
- [x ] Small (phone)

## Before you submit
- [x ] Yes, I have tested this issue thoroughly
- [ ] Yes, I have attached screenshots and/or screencast of the issue in action
- [ ] Yes, I have included any relevant debug data and error logs

**Comment by jaedb** [comment]
This behavior is quite subjective, and has been thoroughly discussed in previous issues.

Tapping on a track, by design, does nothing. This is because a track element has sub-clickable elements (like the artist or album links). To interact with a track, you must select it using the radio button. 

The other consideration is that this is an interface that any number of users can be using at any given time. This users can vary in level of computer literacy, and thus their behavior can be a little challenging. Imagine the frustration for all users when one user has the habit of clicking a track, which wipes the current queue and plays the single track they clicked on.

As such, this is not something that I am looking to change at this time.
