### ISSUE TITLE
I have to login to spotify everytime

### ISSUE THREAD

**Issue by vojtapolasek** [jaedb/Iris#21]
Hi,
I don't know if this can be addressed, but I have to log into spotify through Iris settings everytime I start Mopidy. And even everytime I leave the Iris page and visit it again without stopping Mopidy. Is this expected?

**Comment by jaedb** [comment]
This is not expected. The tokens are stored in `localStorage` which is essentially an HTML5 cookie. However if you have disabled cookies, are in incognito mode or otherwise disable local caching this would not work.

Please check your browser config and/or another browser to see if the issue persists. Also, what browser and version (and OS) are you working on?

**Comment by jaedb** [comment]
@vojtapolasek any progress on this? It'd be great to figure out what's causing this to break for you.

**Comment by vojtapolasek** [comment]
Hi, it seems that it was caused by an addon which deleted cookies after
I left the site. Sou I think you can close this.
