### ISSUE TITLE
Privacy policy for usage of personal information

### ISSUE THREAD

**Issue by zolaemil** [jaedb/Iris#229]
With all due respect, is reporting Spotify user IDs to Google Analytics strictly necessary?

https://github.com/jaedb/Iris/blob/master/src/js/services/spotify/middleware.js#L415

**Comment by jaedb** [comment]
By being able to identify individual users, I am able to more accurately trace issues that users experience. For example, Spotify users who were linked as a Facebook user have a numerical `user_id` (instead of a string, like `jaedb`. These users were experiencing issues when viewing their profile as a result. By having this data in Google Analytics I was able to ascertain a pattern, and apply a fix to Iris much more quickly.

So to answer your question, no it's not strictly necessary. My opinion is that if including it in Analytics results in a better quality piece of software, then it's worth it.

**Comment by zolaemil** [comment]
I understand the benefits. However, I find it somewhat unexpected from an open source software to collect and transfer personally identifiable information to a central location. 

I also understand that the software is provided "as is", but I think it would be nice to disclose this and provide some kind of reassurance (maybe in the form of a simple privacy policy statement) as to what way the information will be used.

**Comment by jaedb** [comment]
At this stage I think the best course of action is better communication about what exactly is logged. This will form the basis of a (very) light privacy policy.

**Comment by jaedb** [comment]
Privacy policy can now be found [here](https://github.com/jaedb/Iris/wiki/Terms-of-use), and the software (_Settings > About_) itself also notifies the user of collection of any personal information.

**Comment by zolaemil** [comment]
Thanks @jaedb. 

@renekliment I agree, the ability to opt-out would be even better. Would you like to open another issue requesting this feature?
