### ISSUE TITLE
Radio function not working 

### ISSUE THREAD

**Issue by loudandbeyond** [jaedb/Iris#255]
Hey guys 

I just update my Iris version and now I am having troubles playing radio direct from the spotify artist, function which works really great with the previews version... Any idea how can I fix this or how I can downgrade the version ?... Thank you in advanced for the attention.

**Comment by jaedb** [comment]
@loudandbeyond please use the issue template (which you saw when creating this issue) and ensure you provide all information.

**Comment by jaedb** [comment]
@loudandbeyond Also, what version did you upgrade from (and to)? The more information you provide the quicker I can investigate the issue.

**Comment by JustinHop** [comment]
I write a lot of python, let me know if you need any more info.

## Expected behavior
Clicking start radio context menus over a radio startable object should start radio based on object.  Everything else appears to be working
## Actual behavior
Popup in web interface in lower right stating radio is starting, followed by an error message saying it failed.
## Steps to replicate
1. Right click any artist, album, song, etc.
2. Select start radio

## Tested environment(s)
#### Operating systems affected
- [ ] Windows:
- [ ] Mac: 
- [ X] Linux:  Ubuntu 16.04, Virtualenv python 2.7.8
- [ ] iOS: 
- [ ] Andriod:
- [ ] Other:

#### Browsers affected
- [X ] Chrome: 
- [ ] Firefox: 
- [ ] Internet Explorer:
- [ ] Opera: 
- [ ] Other:

#### Screen sizes affected
- [ X] Huge (ie desktop)
- [ ] Large (ie laptop)
- [ ] Medium (ie slim laptop/tablet)
- [ ] Small (phone)

## Additional details, debug data, logs, etc
% pip freeze
adns-python==1.2.1
alabaster==0.7.9
ansible==2.1.1.0
apipkg==1.4
appdirs==1.4.3
arrow==0.10.0
attrs==16.0.0
autopep8==1.2.4
Babel==2.3.4
backports-abc==0.5
backports.ssl-match-hostname==3.5.0.1
BeautifulSoup==3.2.1
beautifulsoup4==4.5.3
binaryornot==0.4.0
BitTorrent==3.4.2
blinker==1.4
boto==2.42.0
bzr-etckeeper==0.0.0
cachetools==2.0.0
calendar-indicator==0.3.1
certifi==2018.1.18
cffi==1.11.4
characteristic==14.3.0
chardet==3.0.4
Cheetah==2.4.4
click==6.7
configobj==5.0.6
contextlib2==0.5.5
cookiecutter==1.5.1
coverage==4.2
cryptography==1.4
debtags==2.0
decorator==4.0.11
defer==1.0.6
defusedxml==0.4.1
deluge==1.3.12
dirspec==13.10
DisplayCAL==3.1.0.0
dnspython==1.14.0
docopt==0.6.2
docutils==0.12
driconf==0.9.1
duplicity==0.7.6
ecdsa==0.13
enum34==1.1.6
execnet==1.4.1
funcsigs==1.0.2
future==0.16.0
gcalcli==3.3.2
gdata==2.0.18
GeoIP==1.3.2
globs==0.2
gmusicapi==10.1.1
google-api-python-client==1.5.2
googlecl==0.9.13
gpsoauth==0.4.1
gyp==0.1
html5lib==0.999999999
httplib2==0.10.3
idna==2.6
imagesize==0.7.1
imaplib2==2.53
infoblox==1.1.1
iniparse==0.4
iotop==0.6
ipaddress==1.0.19
IPy==0.83
Jinja2==2.8
jinja2-time==0.2.0
Landscape-Client==16.3+bzr834
lockfile==0.12.2
lxml==3.6.4
M2Crypto==0.25.1
Magic-file-extensions==0.2
Mako==1.0.4
Markdown==2.6.6
MarkupSafe==0.23
MechanicalSoup==0.6.0
mercurial==3.9
mock==2.0.0
Mopidy==2.1.0
Mopidy-GMusic==2.0.0
Mopidy-InternetArchive==2.0.0
-e git+https://github.com/jaedb/Iris.git@54bf70087143f0a30a55fa0aebf9665cc7eec794#egg=Mopidy_Iris
mopidy-lcd==1.2.1
Mopidy-Local-Images==1.0.0
Mopidy-Local-SQLite==1.0.0
Mopidy-Podcast==2.0.1
Mopidy-Qsaver==0.2.6
Mopidy-Scrobbler==1.1.1
Mopidy-SoundCloud==2.0.2
Mopidy-Spotify==3.1.0
Mopidy-Spotify-Tunigo==1.0.0
Mopidy-Spotify-Web==0.3.0
Mopidy-Subsonic==1.0.0
MPNotifier==1.1
mutagen==1.37
mysql-connector-python==2.0.4
mysql-utilities==1.6.1
ndg-httpsclient==0.4.2
netaddr==0.7.18
notify2==0.3
numpy==1.11.1
oauth2client==4.0.0
oauthlib==1.1.2
offlineimap==7.0.6
oneconf==0.3.9
ordereddict==1.1
packaging==16.8
PAM==0.4.2
paramiko==2.0.2
parsedatetime==2.1
pbr==2.0.0
pep8==1.7.0
Pillow==3.3.1
piston-mini-client==0.7.5
PlexAPI==2.0.2
ply==3.8
poyo==0.4.1
proboscis==1.2.6.0
protobuf==3.2.0
psutil==4.3.0
py==1.4.31
py-sonic==0.5.1
pyalsa==1.0.29
pyasn1==0.2.3
pyasn1-modules==0.0.8
pycountry==1.20
pycparser==2.18
pycrypto==2.6.1
pycryptodome==3.4
pycryptodomex==3.4.5
pycryptopp==0.6.0.1206569328141510525648634803928199668821045408958
pycups==1.9.73
pycurl==7.43.0
pyenchant==1.6.8
pygame==1.9.2b8
Pygments==2.1.3
pygobject==3.20.0
pygraphviz==1.3.1
PyICU==1.9.3
PyJWT==1.4.2
Pykka==1.2.1
pylast==2.0.0
pyliblo==0.10.0
pyliblzma==0.5.3
pyOpenSSL==16.0.0
pyparsing==2.2.0
pyrit==0.4.0
pyserial==3.1.1
PySocks==1.5.0
pyspotify==2.0.5
pysqlite==2.8.2
pytest==3.0.0
pytest-cache==1.0
pytest-cov==2.3.1
pytest-pep8==1.0.6
pytest-timeout==1.0.0
python-apt==1.1.0b1
python-cloudfiles==1.7.11
python-dateutil==2.6.0
python-debian==0.1.28
python-gflags==3.0.6
python-libdiscid==0.4.1
python-libtorrent==1.0.7
python-mpd==0.3.0
python-twitter==3.1
python-vim==0.3
pytz==2016.6.1
pyudev==0.21.0
pyxdg==0.25
PyYAML==3.11
raven==6.5.0
requestbuilder==0.5.2
requests==2.18.4
requests-cache==0.4.13
requests-oauthlib==0.6.2
roman==2.0.0
rope==0.10.3
ropemode==0.3
ropevim==0.7.0
rpm-python==4.12.0.1
rsa==3.4.2
scapy==2.3.2
scour==0.32
selenium==2.53.6
service-identity==16.0.0
simplejson==3.8.2
singledispatch==3.4.0.3
six==1.11.0
smbus==1.1
snowballstemmer==1.2.1
SOAPpy==0.12.22
software-center-aptd-plugins==0.0.0
spectacle==0.25
Sphinx==1.4.6
sphinx-rtd-theme==0.1.9
spotipy==2.4.4
SQLAlchemy==1.0.14
stevedore==1.21.0
tornado==4.5.3
ttop==0.9.1
tunigo==1.0.0
Twisted==16.3.2
Twisted-Lore==15.2.1
typing==3.5.2.2
uritemplate==0.6
uritools==2.1.0
urlgrabber==3.9.1
urllib3==1.22
validictory==1.1.0
vboxapi==1.0
virtualenv==15.0.3
virtualenv-clone==0.2.6
virtualenvwrapper==4.7.2
vobject==0.9.2
webencodings==0.5
whichcraft==0.4.1
wstools==0.4.4
wxPython==3.0.2.0
wxPython-common==3.0.2.0
yum-metadata-parser==1.1.4
zenmap==7.1
zope.interface==4.2.0

Corresponding error log lines
ERROR    2018-02-21 10:57:57,347 [23129:HttpServer] mopidy_iris.core
  IrisFrontend: access_token missing or invalid
ERROR    2018-02-21 10:57:57,347 [23129:HttpServer] mopidy_iris.core
  No recommendations returned by Spotify

mopidy.conf

[file]
enabled = true
follow_symlinks = true

[logging]
#console_format = %(levelname)-8s %(message)s
#debug_format = %(levelname)-8s %(asctime)s [%(process)d:%(threadName)s] %(name)s\n  %(message)s
#debug_file = mopidy.log
#config_file =

[loglevels]
#cherrypy = warning
#pykka = info

[audio]
mixer = software
mixer_track = 
output = autoaudiosink
#visualizer = 

[proxy]
#scheme = 
#hostname = 
#port = 
#username = 
#password = 

[scrobbler]
enabled = true
username = REMOVED
password = REMOVED

[http]
enabled = true
hostname = 127.0.0.1
port = 6680
#static_dir =
#zeroconf = Mopidy HTTP server on $hostname

[m3u]
enabled = true
#base_dir = /home/justin/Music
#default_encoding = latin-1
default_encoding = utf8
default_extension = .m3u8
playlists_dir = /home/justin/.mpd/playlists


[mpd]
enabled = true
hostname = 127.0.0.1
port = 6602
password = 
max_connections = 20
connection_timeout = 60
zeroconf = Mopidy MPD server on $hostname

[local]
enabled = true
media_dir = /home/justin/Music
playlists_dir = /home/justin/.config/mopidy/local/playlists
tag_cache_file = /home/justin/.config/mopidy/local/tag_cache
scan_timeout = 1000
excluded_file_extensions = 
  .html
  .jpeg
  .jpg
  .log
  .nfo
  .png
  .txt

[stream]
enabled = true
protocols = 
  http
  https
  mms
  rtmp
  rtmps
  rtsp

[spotify_web]
enabled = false
client_id = REMOVED
client_secret = REMOVED

[soundcloud]
enabled = true
explore_songs = 30
auth_token = REMOVED
#
[spotify]
enabled = true
username = 12157003140
password = 4butthead
bitrate = 320
toplist_countries = US
client_id = REMOVED
client_secret = REMOVED
timeout = 30

[spotify_tunigo]
enabled = false
region = US
cache_time = 86200

[audioaddict]
enabled = false
#username =  REMOVED
#password = TurCuRel
#quality = 320k
#difm = true
#radiotunes = true
#rockradio = true
#jazzradio = true
#frescaradio = true

[internetarchive]
enabled = false

[subsonic]
enabled = false

[mopidy-local]
enabled = true

[gmusic]
enabled = false
username = REMOVED
password = REMOVED
all_access = true
radio_stations_as_playlists = false
radio_tracks_count = 40
bitrate = 320
deviceid = 6FD4DD1CBE246598

[qsaver]
enabled = true
#backup_file = /home/justin/.config/mopidy/mopidy_tracklist_backup.json
backup_file = ./mopidy_tracklist_backup.json

[iris]
enabled = true
country = us
locale = en_US


## Before you submit
- [X ] Yes, I have tested this issue thoroughly
- [ ] Yes, I have attached screenshots and/or screencast of the issue in action
- [X ] Yes, I have included any relevant debug data and error logs

**Comment by loudandbeyond** [comment]
Hey guys ! Sorry for my delayed reply !! Now everything is working great ! Thank you so much !

**Comment by JustinHop** [comment]
No worries. Good luck. I'll try again with latest master.

**Comment by JustinHop** [comment]
Confirmed behavior on master 7ef9eb5b94501b7978f0d5ce77feeac1001d10ab

**Comment by JustinHop** [comment]
Not sure if this is related. I got this log line

ERROR    2018-02-21 11:44:08,394 [9032:SpotifyBackend-7] mopidy_spotify.web
  Fetching https://auth.mopidy.com/spotify/token failed: 401 Client Error: UNAUTHORIZED for url: https://auth.mopidy.com/spotify/token

**Comment by jaedb** [comment]
@JustinHop You've confirmed behavior as working or still experiencing issues?

The error you posted for `mopidy_spotify.web` appears to indicate your config file credentials are invalid. As this is an error posted by the `SpotifyBackend` it isn't an issue with Iris (although it will affect your ability to play Spotify tracks).

**Comment by JustinHop** [comment]
Yeah, my config has spotify_web with enabled = false. Not sure why its coming up.

**Comment by JustinHop** [comment]
OK, Not an issue with Iris. Mopidy Spotify and Mopidy Spotify Web and upgraded their authentication methods. 
Following the new auth directions included in Mopidy Spotify Webs code resolved the issue.

Thanks for the help

**Comment by jaedb** [comment]
Glad you guys have got things working again.
