### ISSUE TITLE
Could not load profile

### ISSUE THREAD

**Issue by brknkfr** [jaedb/Iris#283]
## Expected behavior

Working Iris ...

## Actual behavior

Upon calling Iris, which is running as a service running on a server, there first a message "Could not load profile".

Login via spotify works, but shortly after that, multiple message boxes in red are appearing:

- "Could not load profile"
- "Could not load version"

Or upon clicking specific elements:

- "Could not load library playlists"
- "Could not load featured playlists"

## Steps to replicate
1. Call mopidy-iris via browser on remote server and try to play something
2.

#### Operating systems affected
- [ ] Windows:
- [ ] Mac: 
- [x] Linux: Debian Stretch / mopidy, mopidy-spotify and mopidy-local-sqlite installed via packet manager and mopidy-iris installed via "pip install mopidy-iris" (version 3.17.4)
- [ ] iOS: 
- [ ] Andriod:
- [ ] Other:

#### Browsers affected
- [x] Chrome: 
- [x] Firefox: 
- [ ] Internet Explorer:
- [ ] Opera: 
- [x] Other: Epiphany, Chromium, etc

#### Screen sizes affected
- [x] Huge (ie desktop)
- [x] Large (ie laptop)
- [x] Medium (ie slim laptop/tablet)
- [x] Small (phone)

## Additional details, debug data, logs, etc

mopidy deps: https://paste.momou.ch/?6733f2d407f15d11#vjN2pu9ywZ8QWxkyVk5C4fUhn01e/agbzaLRocQr6qo=
mopidy config: https://paste.momou.ch/?4853015448bcc9af#NHr+UyhHjLXb/d8+wjjDZlCmtXSQn+Y9Z2ptx8gaW/Q=
mopidy log upon starting: https://paste.momou.ch/?42a95e7ba8ed1d5b#s+tWXD6pbt9mLPq2KAi2yuxOXhVt3zehofC4QZNrv8E=

## Before you submit
- [x] Yes, I have tested this issue thoroughly
- [x] Yes, I have attached screenshots and/or screencast of the issue in action
- [ ] Yes, I have included any relevant debug data and error logs

**Comment by jaedb** [comment]
Is this a fresh install? Can you try _Settings > Reset all settings_ to see if this makes any difference?

**Comment by brknkfr** [comment]
It's a fresh installation. _Settings > Reset_, event with a fresh browser profile doesn't make any difference.

**Comment by brknkfr** [comment]
I did a pip `uninstall mopidy-iris`, cleaned all the pip-packages and reinstalled it again with `pip install mopidy-iris`. The deps (mopidy deps) are the same and the "Could not load profile" still appears and now I can't even login to spotify (exactly this one https://github.com/jaedb/Iris/issues/282#issuecomment-383289034)

**Comment by brknkfr** [comment]
I don't know why, but Loading playlists etc works again, just spotify login doesn't work. I'll reopen #282

**Comment by GuzziGuy** [comment]
I'm now getting the same problem on the latest release - 3.41.2. I did have it working but then upgraded my installation (I don't remember the previous version, sorry!) and now I am getting the same issue as brknkfr reported.

This is not the the same as #282 because when I clock log in, it proceeds as expected to the Spotify auth page. But when I click Agree, I see:

- Current user: Unknown
- Authorization: Log out (implying it's logged in)

I've reset all the settings, reinstalled Iris, restarted Mopidy.

- I **can** go to Browse > Spotify > Top albums etc - I can play from there although it generates red warnings for 'Could not load track'.

- But I can't go to eg Discover > Genre/Mood - a red warning appears 'Could not load genres'

Any ideas what I'm missing, or how best to trace/debug?
