### ISSUE TITLE
Web audio stream on Icecast breaks when selecting another track

### ISSUE THREAD

**Issue by Ismas** [jaedb/Iris#293]
## Expected behavior
Playback should continue when changing to another track. 

## Actual behavior
Pressing "next", "previous" or any other track audio cache flushes (2-3 seconds) then stream stops.
Refreshing the page with F5 recovers the stream.
When playing track ends, new track starts playing normally.

## Steps to replicate
1. Activate and configure Icecast stream
2. Select one track. Plays normaly
3. Select other track. Audio stop and new one does not play.
4. Press F5. Stream starts in the new track.

#### Operating systems affected
- [ X] Windows: 10
- [ X] Mac: 
- [ X] Linux: Ubuntu 16.04 updated

#### Browsers affected
- [ X] Chrome:  67.0.3396.62 (Build oficial) (64 bits)
- [X ] Firefox: 60.0.1 64 bits 

## Additional details, debug data, logs, etc
Iris version 3.20.0 , (better than 3.19 where stream didn't star, thank you :)
Network traffic monitored. It's not an audio issue, data stream does stop when changing track.

## Before you submit
- [ X ] Yes, I have tested this issue thoroughly

**Comment by Ismas** [comment]
As further info, I configured <fallback-mount> on Icecast2 to no avail. Seems interface doesn't reconnect icecast when changing tracks.

**Comment by Ismas** [comment]
Ok. It seems a Mopidy issue, it closes the mountpoint and opens a new one on changed track. 
Mopidy version 2.1.0. 

I think a workaround could be check and wait until mountpoint is available, then reconnect.

**Comment by jaedb** [comment]
I believe the issue is that Iris only injects the `<audio>` tag when `play_state == "playing"`. When a track ends, I think `play_state` becomes `"stopped"` for a very brief moment. This would remove the `<audio>` tag, only to be re-injected a moment later, causing the audio stream to start from the beginning of it's cache.

A possible fix would be to attempt cache clearing by issuing a track-based URI cache clearing property to the `<audio>` tag's URL (ie `.../stream.mp3?cache=spotify:track:123`).
