### ISSUE TITLE
Profile Unauthorized

### ISSUE THREAD

**Issue by Wqrld** [jaedb/Iris#309]
## Expected behavior
I can also use iris as a web app.
## Actual behavior
Im getting the error: `profile Unauthorized`
## Steps to replicate
1. create a chrome web app with
` C:\Users\werel\AppData\Local\Google\Chrome\Application\chrome.exe -app=http://192.168.178.220:6680/iris/`
2. Launch it

## Tested environment(s)
Windows 10 with the newest chrome stable
#### Operating systems affected
- [x ] Windows:
- [ ] Mac: 
- [ ] Linux: 
- [ ] iOS: 
- [ ] Andriod:
- [ ] Other:

#### Browsers affected
- [x ] Chrome: 
- [ ] Firefox: 
- [ ] Internet Explorer:
- [ ] Opera: 
- [ ] Other:

#### Screen sizes affected
- [x ] Huge (ie desktop)
- [ x] Large (ie laptop)
- [x ] Medium (ie slim laptop/tablet)
- [x ] Small (phone)

## Additional details, debug data, logs, etc
```
Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
api.spotify.com/v1/me:1 Failed to load resource: the server responded with a status of 401 ()
middleware.js:95 Could not load your profile Unauthorized. Object
(anonymous) @ middleware.js:95
```
## Before you submit
- [ x] Yes, I have tested this issue thoroughly
- [x ] Yes, I have attached screen
![problem](https://user-images.githubusercontent.com/13834197/41906206-915c7e66-793d-11e8-92a7-0d256669499a.PNG)
shots and/or screencast of the issue in action
- [x ] Yes, I have included any relevant debug data and error logs

**Comment by jaedb** [comment]
I believe the 401 error was actually a bug during the migration of the Spotify authorization gateway :-)

Do you still encounter this error?

**Comment by jaedb** [comment]
Can you try clearing your browser cache? Chrome tends to cache redirects quite heavily which is why this is likely to be happening. Even a hard refresh might do it.

**Comment by Wqrld** [comment]
Doesn't seem to work, im still getting a 400 on https://jamesbarnsley.co.nz/iris/auth_spotify.php?action=refresh&refresh_token=false

**Comment by jaedb** [comment]
I've just noticed the URL you're using doesn't have the `refresh_token` value (ie it's `false`). This is why you're getting the error; you need to have a `refresh_token` in order to get a new `access_token`.

It is unusual that your `refresh_token` is missing. It's possible it is due to a previous issue during the authorization process. I would suggest re-authorizing your Spotify account, or reset all settings.

**Comment by Wqrld** [comment]
That worked. I would swear that it didn't work the last 2 times i tried.

**Comment by Wqrld** [comment]
closing as i can't reproduce it anymore. Thanks for this awesome program!

**Comment by varunagrawal** [comment]
I encountered this issue and I think I found the reason. I logged into Spotify on Iris from my laptop and then accessed Iris from my phone. My phone browser showed me all the spotify data (tracks, playlists etc) so I didn't think anything was wrong until every time I would get 401 Unauthorized errors whenever I tried doing something.

Turns out, I wasn't logged into the Spotify on my phone browser via Iris. Once I did that, everything worked well. I guess that may be a bug?
