### ISSUE TITLE
Make Iris GDPR compliant

### ISSUE THREAD

**Issue by allo-** [jaedb/Iris#317]
## Expected behavior

Iris should obey privacy laws

## Actual behavior

Iris does not, because it defaults to data collection.

## Steps to replicate
1. open the iris webinterface
2. Sending statistics is switched on by default (it has to be opt-in instead of opt-out to comply)

SSL is switched off by default as well, but this may be only because I have no TLS configured at the mopidy server.

**Comment by jaedb** [comment]
By only collecting _anonymous_ usage information, *Iris is already GDPR compliant*. Anonymous means to be in no way connectable to an individual.

The opportunity to opt-out of anonymous usage reporting is not equivalent to a user refusing consent to collect personally identifyable data (which _would_ require a default of being unchecked).

**Comment by allo-** [comment]
Isn't it using Google Analytics, which is not compliant? Don't be fooled by what companies call "anonymous", what matters is what they have in their database, even when it may not be accessible to you.

**Comment by allo-** [comment]
Sorry, when I am insisting on such a detail, but as EU citizen it is relevant to me to have contracts with all third-party services which collect data and rely on opt-in instead of opt-out.
Using wrong default may be dangerous for your users.

**Comment by mczerski** [comment]
https://www.blastam.com/blog/5-actionable-steps-gdpr-compliance-google-analytics

**Comment by allo-** [comment]
The problem is, that it starts with as basic things as that loading ga transmits your IP address. I need to have a data processing contract with Google,in which they assert me, that they really do not store it and then need to assert the user, that I made sure it is not stored.
As it is your Google analytics, I would need a contract with you, that you do not store data *and* have contracts with all services you use to process data.

In principle I would more wish for a server config option to disable even the checkbox, as I even with informed consent would need a contract with you, that you do not do more than the user agreed on.

Speaking of informed consent, such a checkbox needes a link to a privacy policy. Some people even say you need one saying"I store nothing" if you do not store anything (But no further consent from the user then, as you don't do anything which requires consent then).

Yes, this IS complicated. That's why I do not use such services at all.

**Comment by DanH42** [comment]
I'm going to try to enumerate some of the reasons why everything @jaedb said when closing this issue is factually incorrect, and this issue needs to be reopened.

- Iris collects user data using Google Analytics. I can't believe I need to say this, but allowing an advertising company to place cookies on a user's system is not anonymous. Right off the bat, if you're using Google Analytics, you need opt-IN consent, period.
- Even if we pretended it was possible for Google Analytics to ever be used anonymously, it certainly doesn't behave that way out of the box. For example, as mentioned in the article linked above, Google Analytics collects users' IP addresses by default, and this needs to be disabled in the client. In Iris' case, that means calling `ReactGA.set({ anonymizeIp: true });` on initialization, which I don't see happening anywhere.
- Even if Iris was asking Google not to store users' IP addresses, it's still [sending unique identifiers](https://github.com/jaedb/Iris/blob/master/src/js/services/spotify/middleware.js#L188-L192) for users, allowing both Google and anyone with access to the GA property to track the same individual across multiple devices. Hashing usernames is slightly better than sending them raw, but the resulting (unsalted!) hash is still often going to be reversible back to its original value via either rainbow tables or direct cracking. If you sent me a list of all the user ID hashes you've collected so far (please don't), I _promise_ that I could give you back a list of usernames. Calling this anonymous is disingenuous at best.
  - SHA256 hashes are actually [the exact method Facebook uses](https://developers.facebook.com/docs/marketing-api/audiences/guides/custom-audiences#example_sha256) to collect user re-identification information from advertisers.
  - Less than a year before this issue was opened, @jaedb was [openly _defending_ collecting raw user IDs without consent](https://github.com/jaedb/Iris/issues/229#issuecomment-343277891), which is honestly appalling. I find it hard to trust any claims of privacy protection after seeing that.
- Google Analytics still gets loaded on the initial-setup screen, so even users who opt out will have their data collected by Google unless they have additional security measures in place to prevent the tracking code from loading.

Iris' 3-sentence [privacy policy](https://github.com/jaedb/Iris/wiki/Terms-of-use#privacy-policy) is kind of a mess too:

> All personally-identifying data (names, usernames, email addresses, etc) is anonymized by Iris using md5 encryption before collection. This enables the continued development and improvement of Iris while protecting your privacy.
> 
> Additionally, as at version 3.21, users can opt out of usage statistics collection.

- It doesn't state that data is shared with any third parties, let alone listing who those parties are.
  - There's no mention that data is collected by Google, a company that users are likely to already have opinions about, and not just by the developer directly.
  - Iris also shares data with Sentry.io, which I only discovered today as I was digging through the tracking code (I'm running an old version of Iris from before this was introduced, or my ad blocker would have tipped me off).
  - The privacy policies of both Google Analytics and Sentry should be linked here, along with those of any other third parties Iris sends data to.
- It also fails to mention that despite being hosted by the owner of the Mopidy instance, [Iris proxies authentication data through the developer's personal website](https://github.com/jaedb/Iris/blob/master/src/js/store/index.js#L94-L103). I assume/hope that data isn't being logged anywhere, but that should _really_ be stated explicitly. It would also be a really good idea to provide the source code for those scripts somewhere prominent, both to establish some trust that it's handling sensitive user data properly and also to allow users to easily host their own if they desire.
- In addition to simple hashing being insufficient as a privacy measure, the description of how it's done is incorrect. Hashing is done with SHA256 rather than MD5 as of #355, which means the privacy policy has been out of date for over 4 years, despite that very sentence having been updated once since the change was made.
  - Also, hashing is not the same as encryption. I really hope I don't need to elaborate on this, but it's a concerning mistake to make when this is the only layer that's even sort of trying to protect users' privacy when sending analytics.
  
So:
- Iris collects information that can be connected to individuals
- Iris _does not_ only collect anonymous usage information
- Iris is not GDPR compliant

People who self-host open source software don't generally expect it to report on their behavior to ad companies. I use browser extensions to block tracking on most of my machines, but Mopidy (and by extension Iris) is something I sometimes use from more limited systems that I don't use for general web browsing, and so aren't always set up with the full suite of protections I generally have elsewhere. In fact, the whole reason I started using Mopidy and Iris was as an alternative frontend for Spotify (RIP mopidy-spotify), with one of the goals being better privacy over their official clients. I expect to be able to hold self-hosted software like Iris to a _higher_ standard than the broader web. To get that out of Iris, I have to modify its source code directly, which disincentivizes me from updating.

You've said before that data collection "results in a better quality piece of software," but I would assert that software that doesn't respect users' privacy or consent cannot be quality software. You've been getting pushback on the use of Google Analytics since [before Iris was even called Iris](https://github.com/jaedb/spotmop/issues/47#issuecomment-254848333), so you have to realize how unpopular this is. I understand the desire to know more about how people are using your software, but that shouldn't come at the cost of informed consent. If your argument against explicit opt-in tracking is that most users wouldn't turn it on, that's a tacit admission that you understand that those people don't want to be tracked, and you want to track them in spite of that knowledge.

There's a number of possible solutions to this problem with varying complexity and benefits, all of which have been suggested before, but my personal top picks are probably:
- Remove the tracking code entirely
- Add a server-side configuration option to completely disable tracking for all clients
- Make tracking opt-in instead of opt-out

Any of these solutions would address the majority of issues outlined above. The only remaining thing I can think of is the authentication proxies, which are already possible to configure to use different endpoints, so simply providing the (hopefully very simple) source code for those PHP scripts should give users all the tools they need to run a truly private copy of Iris.

**Comment by jaedb** [comment]
@DanH42 I can see you've put a lot of thought and effort into your post - nice!

In the spirit of a productive open-source conversation, it is worthwhile looking at ways that _you_ too can contribute to improvements. You've made some suggestions on how to rectify the issues that you've raised - would you be open to creating pull requests for these?
