### ISSUE TITLE
Duplicated login names

### ISSUE THREAD

**Issue by pablitok** [jaedb/Iris#323]
Different logins from differents machines can have the same name in /iris/#/settings/service/spotify

**Comment by jaedb** [comment]
Please use the issue template when logging issues. Without this I can't quickly replicate the issue, which means it won't get seen to.

**Comment by jaedb** [comment]
I'm closing this issue as it's not actionable, and appears to have gone stale.

If you feel this is unresolved, please feel free to reopen.

PS. The `username` in Iris provides no level of authentication; it is simply a mechanism to identify each client (instead of by it's GUID). As such there is no need for it to be enforced as unique.
