### ISSUE TITLE
No artwork in albums

### ISSUE THREAD

**Issue by fmarzocca** [jaedb/Iris#364]
## Expected behavior

Show Albums artwork
## Actual behavior

No artwork

Hi,

I am running Iris 3.32.4, mopidy 2.2.1 on a Raspberry PI3 with Rasbian Stretch.

It is working fine, but I am missing Albums artwork. I have them in Artists, but not in Album. Is there anything I should configure?

Thanks

**Comment by jupe76** [comment]
If your album artwork consists of local files as folder.jpg or cover.jpg:

Did you install and set up [mopidy-local-images](https://github.com/mopidy/mopidy-local-images) ?

**Comment by fmarzocca** [comment]
Aren’t images downloaded from external services?

Il giorno ven 15 feb 2019 alle 18:43 jupe76 <notifications@github.com> ha
scritto:

**Comment by fmarzocca** [comment]
I thought that Atrwork is coming from Last.fm. As I can see "Artist" atwork (without having any local image file), why Iris is not showing the Album artwork?

**Comment by jaedb** [comment]
__Album__ art is only loaded from _Mopidy-Local-Images_. __Artist__ images are only loaded from Last am because there is no Mopidy structure to provide artist images.

So the reason you're not getting album art is because your library doesn't provide it, or you haven't installed _Mopidy-Local-Images_.

I hope this helps explain how things work!

**Comment by fmarzocca** [comment]
Ah, ok. I asked this question because last month I was using another webclient (musicbox) and I had Album images in there, so I thought to have them in Iris too.

Thanks for explanation. So, I have to remain with blank artworks in Albums.
