### ISSUE TITLE
[Feature Request] Add album cover artwork from LastFM

### ISSUE THREAD

**Issue by fmarzocca** [jaedb/Iris#369]
Please add album cover art from LastFM instead of (or in addition to) local embedded images, like other clients do (i.e. musicbox-webclient, MPDroid, etc.)

**Comment by jaedb** [comment]
My initial reaction is that I've discussed this thoroughly with you already, and minimal use of LastFM API was deliberate. 

However, after further thought I think it might be more feasible than first appeared.

LastFM's restrictions appear to be _IP address-based_ rather than _key-based_ so this means that _only your_ requests will get rejected if you spam their servers with no effect to other Iris users (unlike most other APIs).

**Comment by fmarzocca** [comment]
Yes, that's why I have raised this FeatReq.  In addition, I thought that you already have a piece of code in app.js that could (maybe) easily revamped.
Thanks.
