### ISSUE TITLE
Add everything from an Artist to play queue

### ISSUE THREAD

**Issue by allo-** [jaedb/Iris#395]
I would like an option on the artist page to play everything from this artist and not only the top tracks.

Copying the Artist URI and inserting it with a MPD client works, but I cannot find an UI option in Iris.

**Comment by jaedb** [comment]
There is a major performance knock-on to this. It would work fine(ish) for local content, but external content (ie Spotify) would require an external request for every individual album and track. The current versions of Mopidy will lock up until all requests are complete.

To achieve this I would need to build the similar logic to adding playlist tracks (where you get a blue process message). This is a large project, so there would need to be large number of users would would benefit from it to justify its development.

Side note: were you prompted to select a template when creating the issue?

**Comment by allo-** [comment]
I am not sure, but the MPD API seems to allow this without a performance hit.

Steps:
- Search for something (source: database, type: any)
- Sort by URL (so spotify:album comes first, then spotify:artist)
- Select the spotify:artist URL and select "replace"
- It takes 3 seconds to add about 100 songs

I think the key point here is, that the interface does not do the lookup, but adds a meta-url ``spotify:artist:ID`` that is resolved by mopidy (or the libspotify itself?).

I am not sure how the web api works and if there are more limits, but wouldn't it be possible to do the same as a MPD client does?

> Side note: were you prompted to select a template when creating the issue?

I am not sure. I think I was prompted if it is a bug report or a feature request, because it automatically added the label, so probably yes.

**Comment by jaedb** [comment]
Using the _Play_ button for an artist will add the top tracks when they exist (ie only Spotify Artists). Otherwise it'll play the Artist URI, which Mopidy will expand to all of the tracks for said Artist. I believe this solves the original issue.

As a side-note, I have just added a _Play all tracks_ context menu option which will provide some consistency between Spotify and non-Spotify artists. _Play all tracks_ will add the Artist URI to the queue, leaving Mopidy backend to expand this to individual tracks. This will be included in the next release.

**Comment by allo-** [comment]
I think the second part solves the issue for me.
I am looking forward to the next release. Thank you.
