### ISSUE TITLE
Show playlist name in Now Playing

### ISSUE THREAD

**Issue by jaedb** [jaedb/Iris#4]
_From @antons- on December 21, 2016 10:35_

First of all, love the work you have done on this amazing frontend! Thanks heaps!

In our office, person A will add a playlist to the Now Playing queue. Person B, C and D will often ask 'what playlist is that'? This happens every day lol.

It would be cool if Spotmop showed the current playlist name (if any) in the Now Playing area and linked off to it so others in the office can discover the playlist if they like it.

_Copied from original issue: jaedb/spotmop#164_

**Comment by jaedb** [comment]
_From @hcoohb on December 21, 2016 11:5_

Hi,  I like that idea, that would be an awesome feature!

**Comment by jaedb** [comment]
This is a neat idea, and Spotify manages to pull this off in their application. When building this from scratch (as we would need to do) there are a few tricky bits to consider. For example: what if we add other tracks to the queue, at what point have we 'finished' playing the playlist?

**Comment by antons-** [comment]
I would use the Spotify web client as an example for this functionality:

![2](https://cloud.githubusercontent.com/assets/3037189/21584332/4198c80e-d109-11e6-8d06-f516ebf173a8.PNG)

The queue is divided into different tiers:
* Currently playing track (**Don't Let Me Down**)
* Any tracks added via __Play Next__ (**Boss Mode**)
* Any playlists added to queue with their remaining tracks (**Summer Party**) https://play.spotify.com/user/spotify/playlist/103Zi2NG06F9qimASDrszv
* Any tracks added via __Add to queue__

The playlist is finished once all its tracks have been played. At that point, the queue will continue with any remaining tracks (or other playlists) until the queue is empty.

I suspect that the playlist information (if any) will need to be stored alongside the queued track.

Other thoughts - 
* How would reordering the queue work? Will Iris still show the associated playlist in some way?
* Instead of showing the queue as a tier like the Spotify web client - should we instead show that a queued track is part of a playlist by displaying some kind of icon (where the red box is)? The icon will have the playlist title as a tooltip and simply link off to it. This would make reordering the playlist simpler as well.
![3](https://cloud.githubusercontent.com/assets/3037189/21584365/30fb15aa-d10a-11e6-8009-48b5eaee5436.png)

**Comment by jaedb** [comment]
I think the most achievable option is the have a new column _Origin_ that specifies where the tltrack came from. This way we don't reinvent the mopidy tracklist engine.

**Comment by jaedb** [comment]
Some solid progress has been made by creating a _queue metadata_ store that holds both the user who added the track (#16), and where the track came from (if applicable).

You can see this working on the `queue-helper` branch (latest commit 4ccc564). It'd be great if people could give it a spin and let me know if they encounter any bugs.

**Comment by fekete-robert** [comment]
Hi @jaedb , are there any nightly builds for testing it (available via pip/apt), or only the development version you describe in the Readme.md?

**Comment by jaedb** [comment]
Not currently - the only way to test builds is to install via the development methods from the [wiki](https://github.com/jaedb/Iris/wiki/Developing-and-debugging). It may be more involved to setup, but gets you in a position to be able to tweak and test code directly.

**Comment by jaedb** [comment]
Original issue resolved in 2.12.0 58037c8
