### ISSUE TITLE
Does iris require Mopidy-Local-SQLite for browsing local music?

### ISSUE THREAD

**Issue by crocket** [jaedb/Iris#402]
*What part of Iris is your question about?*

My Music > Artists
My Music > Albums
My Music > Tracks

**Your question**

On mpd clients, I can browse genres, albums, and artists.
On http://localhost:6680/iris/, artists, albums, and tracks are empty.

Does it require Mopidy-Local-SQLite? I'm currently using local with local-images.

**Comment by jaedb** [comment]
Yes, Mopidy-Local-SQLite is required to browse using the _My Music > Artists, Albums, etc_ sections. You can otherwise browse your local media under _Browse_.

For the best experience, I recommend using both _Mopidy-Local-SQLite_ and _Mopidy-Images_.

**Comment by crocket** [comment]
Finding local songs by artist, album, etc, ... is pretty much a requirement for me.
Listing Mopidy-Local-SQLite as an optional dependency on README is a bit misleading.

**Comment by jaedb** [comment]
Mopidy-Local-SQLite is listed as a __recommendation__ because it _improves_ the experience. If Iris could not run without it, then listing it as a __dependency__ would definitely be more accurate.

I hope you've managed to get Iris running as desired. I'll close the issue now but please re-open if you feel this has not answered your question.

**Comment by crocket** [comment]
I think you might want to state what one loses in the absence of `Mopidy-Local-SQLite` on README.
