### ISSUE TITLE
Pagination for artist and album view

### ISSUE THREAD

**Issue by sbaier1** [jaedb/Iris#406]
**Is your feature request related to a problem? Please describe.**
When browsing libraries with many items, performance is pretty bad because all items are rendered at once

**Describe the solution you'd like**
Split up artist / album list views into multiple pages based on starting letter or just a fixed count per page.

**Additional context**
It seems none of the current Mopidy web clients do this, but in my opinion it's a pretty essential feature and since this seems to be one of the most well-built web clients i am proposing the feature here.

**Comment by jaedb** [comment]
The current _My Music > Albums_ and _Artists_ views show 50 items initially, and reveal more as you scroll down the list. This a necessary feature for both render performance and to avoid rate-limits of artwork provider APIs.

Unless you are referring to _My Music > Browse > Local Media > Albums_ and _Artists_? You're right in that this can take a very long time to load large libraries. The problem is with the Mopidy server because there is no pagination in Mopidy's `library.browse` API endpoint (or any of its endpoints for that matter).

Unfortunately Iris can't do anything about this.
