### ISSUE TITLE
Subsonic artists/albums not showing up

### ISSUE THREAD

**Issue by peguerosdc** [jaedb/Iris#415]
Hi!

I am running a Subsonic server with [Supysonic](https://github.com/spl0k/supysonic). The problem is that when I go to the Artists/Albums section using the left navigation drawer of the Iris frontend, nothing shows up (even though if I go to Browse > Subsonic > Artists/Album I have all my media displayed).

**My question is:**
Is this feature not implemented for Subsonic backends (I am using [Mopidy Subidy](https://github.com/Prior99/mopidy-subidy))?
Or maybe as Supysonic implements an old version of the Subsonic API (they target v1.9.0 and the details of what's implemented can be checked [here](https://github.com/spl0k/supysonic/blob/master/docs/api.md)), it is breaking this feature (?).

**Some info:**

- Supysonic is running on an arm64 device with armbian.
- Mopidy + Iris is running on macos Mojave 10.14.5
- I don't have the Spotify extension installed for Mopidy.
- Mopidy version: 2.2.2
- Iris version: 3.39.0

Thanks!

**Comment by jaedb** [comment]
In theory all Mopidy backends will display without requiring any extra configuration within Iris. Do you see your _Subsonic_ library in other Mopidy frontends (like the command-line `ncmpcpp`)?

**Comment by mcarlton00** [comment]
I'm also seeing this with my [Mopidy-Jellyfin](https://github.com/mcarlton00/mopidy-jellyfin) extension and so far unable to figure out how to populate artist/album info.  Playlists and Browsing works correctly, but Artists/Albums/Tracks are blank.  `ncmpcpp` works as expected with the media library populated.  I'm guessing it's related to the lookup URIs under Settings/Advanced, but I'm not sure what they should look like.  Mopidy-Jellyfin currently uses a URI scheme along the lines of `jellyfin:artist:$id` and `jellyfin:album:$id`

**Comment by arpena** [comment]
Same thing happens to Mopidy-Dleyna, no Artists/Albums/Tracks showing. Only under Browsing I see the content

**Comment by jaedb** [comment]
All Mopidy backends that support browsing are available under _Browse_. Only Spotify and Mopidy-Local backends are currently supported for browsing in _My Music -> Artists/Albums/Playlists/Tracks_. This is because Mopidy-Local is (more-or-less) built-in, and Spotify has a public HTTP API so they are (relatively) straightforward to work with.

If you wish to have another backend supported in this way, please create a _Feature Request_ issue. Please note that this is quite an involved feature, so the provider (ie Spotify), their API(s) and the Mopidy backend need to be actively supported to justify the effort.
