### ISSUE TITLE
Hifiberry digi+ pro not detected as audio output

### ISSUE THREAD

**Issue by DavidRazdolski** [jaedb/Iris#423]
Hello,

It seems that, for some reason, Iris isn't allowing or isn't able to play audio through my default ALSA device. It's been configured through mopidy and playback works through commands like aplay, yet when actually attempting to play something via Iris (say for example, a spotify song), all it does is offer me the option of "Local Browser" (which does nothing/no sound) or outright no options at all. Here are some relevant outputs that might help in tracking down why this is occurring: 

- `aplay -l`

`**** List of PLAYBACK Hardware Devices ****
card 0: sndrpihifiberry [snd_rpi_hifiberry_digi], device 0: HiFiBerry Digi+ Pro HiFi wm8804-spdif-0 []
  Subdevices: 1/1
  Subdevice #0: subdevice #0`

- `/etc/mopidy/mopidy.conf`

[core]
cache_dir = /var/cache/mopidy
config_dir = /etc/mopidy
data_dir = /var/lib/mopidy

[audio]
mixer = software
output = alsasink

[logging]
config_file = /etc/mopidy/logging.conf
debug_file = /var/log/mopidy/mopidy-debug.log                                                                           
[local]
media_dir = /var/lib/mopidy/media

[m3u]
playlists_dir = /var/lib/mopidy/playlists

[http]
hostname = 0.0.0.0

[iris]
country = us
locale = en_US
[spotify]
username = REMOVED
password = REMOVED
client_id = REMOVED
client_secret = REMOVED
bitrate = 320

[spotify_web]
client_id = REMOVED
client_secret = REMOVED

Playback works fine through terminal commands such as aplay /usr/share/sounds/alsa/Front_Center.wav and all else seems to be working.

Any help/guidance is appreciated in advance :)

**Comment by jaedb** [comment]
This sounds like an issue with Mopidy not sending the audio stream to your device. Iris is just the frontend. The _Outputs_ panel in Iris is used only for _Icecast2_ and _Snapcast_ controls because these are external audio outputs (not system ones like in your scenario).

You would be best to post this question on the [Mopidy repo](https://github.com/mopidy/mopidy/issues).

I use the Hifiberry Amp+ and didn't have any problems, but I'll dig out the config and post this to see if it helps you.
