### ISSUE TITLE
Expose name of person putting song in queue through API

### ISSUE THREAD

**Issue by beaufour** [jaedb/Iris#430]
(I don't know if I should file this with Iris or Mopidy, sorry.)

I have a Slack bot running that posts the next song playing in a channel, and can list the queue, etc. It uses the Mopidy API. But it looks like the person that has added songs to the queue isn't available there, because (I assume) that is handled inside Iris? Any chance that could be exposed through the same API, or another?

**Comment by jaedb** [comment]
You're right - Iris handles the _Added by XX from XX_ information, but Mopidy handles the rest. However Iris does have this available in it's API.

In order to pull this data into your bot you can query Iris with `GET http://MOPIDY_SERVER:MOPIDY_PORT/iris/http/get_queue_metadata` and merge this into your response from Mopidy (`tlid` is the key to joining them).

I hope this helps! Do post your outcome - it's likely to be useful for other Iris users :-)

**Comment by beaufour** [comment]
Oooh, I didn't realize Iris exposed an API too. I'll check it out! And I will share my results here. Although the bot code is so ugly I'm pretty embarrassed by it :) (I am way too rusty to properly deal with async js it seems...)

**Comment by beaufour** [comment]
Finally got around to fixing my setup so I could actually change things in a sane way, and it's working like a charm for song changes:
https://github.com/beaufour/mopidy-slack-bot/blob/4794db0993c76c36fc0a51ad82c391f6cd2cd394/index.js#L72-L95
