### ISSUE TITLE
Inetgrate an alarm clock in Iris

### ISSUE THREAD

**Issue by fmarzocca** [jaedb/Iris#437]
the project [mopidy-alarmclock](https://github.com/DavisNT/mopidy-alarmclock) looks like stalled. It would be nice to have such feature embedded into Iris (with the addition of a sleep timer)...

**Comment by jaedb** [comment]
I would prefer to focus on ensuring Iris continues to do what it does best, rather than filling it with lots of extras that will require continuous maintenance. 

Time is a precious commodity and it's unlikely that the development and maintenance of an alarm clock feature in Iris would get the time it deserves.

You or anyone else interested is welcome to develop this and create a pull request though!
