### ISSUE TITLE
[Feature request] Sorting of Albums/Artists

### ISSUE THREAD

**Issue by sgraca** [jaedb/Iris#46]
Being able to sort list of followed Artists(from Spotify) would be really appreciated. Currently it's not sorted at all.
Also it would be nice to be able to sort album list by artist or title. Currently it's always sorted by artist.

**Comment by jaedb** [comment]
This sorting is a bit challenging, because unfortunately Spotify HTTP API doesn't provide any option to fetch assets pre-sorted. This means when lazy-loading (for obvious performance reasons), each new page of assets will be scattered throughout in accordance with your sort preference.

I do plan to implement sorting regardless as I find it useful too, however it will create it's own UX confusion.

**Comment by jaedb** [comment]
Ready for testing 4980933

**Comment by sgraca** [comment]
I suppose I could cope with the list being reordered while further pages are downloaded. Especially if they could be downloaded automatically without having to scroll to the end of the list. This way I would just click on albums, wait a few seconds and then be able to sort or search the whole list.

**Comment by jaedb** [comment]
I'm resistant to load all items on load as this will affect the performance and UX, especially when a lot of items need loading. This is how _My Playlists_ are loaded and it does create timeout issues (see #36 and #3).

Once your full library has been loaded, it'll persist until you next reset your `localStorage` (ie by refreshing the page).

I have created the sort functionality for Artists and Albums now and it'll be included in the next release.

**Comment by sgraca** [comment]
I upgraded to the newest release and the sorting works great. Thanks! However in the album view sorting by the artist is missing.
