### ISSUE TITLE
Suggestion: Play button replaces current queue

### ISSUE THREAD

**Issue by vojtapolasek** [jaedb/Iris#49]
Just a suggestion. Currently, when pressing "Play" button in Album view or playlist view, it prepends songs before current queue. I personally don't like this and it doesn't seem logical to me. It's maybe only my use case, but I usually browse several playlist before I find the one that I like and I want to play it. I also like to randomize it. But currently I can't do it, because randomization would add all songs from queue and those songs are from previous playlists. But I still can imagine use case when people would like to append playlist/album to current queue, however, I think it is less usual. I can imagine an item in future context menu, something like "Append to queue". But I would like to see change in behavior of the "Play" button sothat it clears current queue and then adds an album/playlist.. What do you think about it?

**Comment by jaedb** [comment]
This was explored in detail some time ago, and it was decided to append the play queue rather than replace it. This is a much less destructive approach, which is important when in a multi-user environment.

See: [spotmop/91](https://github.com/jaedb/spotmop/issues/91) for more.

Regarding _Append to queue_ this already exists as _Add to queue_ in the context menu.
