### ISSUE TITLE
Is it possible to save all settings to all users?

### ISSUE THREAD

**Issue by moloni-pt** [jaedb/Iris#490]
**Your question**
Is it possible that when people access my webserver (like music.example.com), they don't have to pass by the initial setup everytime? 

Right now at home we are 5 people, logging from multiple browsers, and everytime we access on a new one we have to set up everything. 

If we could have all the settings saved server-side and then loaded for everyone, that would be awesome! :)

**Did you want to make a donation to support this support?**
If Iris can do what I want for my home server, I sure will do a donation :)

**Comment by fmarzocca** [comment]
User's setup is saved in a cookie. Enable cookies in the browsers.
What "setup" are you meaning?

**Comment by moloni-pt** [comment]
That one.... Then could I sugest saving it in some file for not making each user set up everything? 
For example, I use a reverse proxy, so when someone logins, they are asked which port to use, and the default there is 80. 

Meanwhile, the port they should use is 6680. 
Now trying to explain what ports are to users that don't know much about it :)

**Comment by fmarzocca** [comment]
I am just an user, but I can tell you that all those settings are stored in the Local Storage of the Browser (username, country, host, port, etc.) and I was never asked to type them again, unless I clear the browser cache, on any computer/smartphone/tablet.

**Comment by moloni-pt** [comment]
Yes, I noticed that. But that makes each "user" have to set the settings like the port and my spotify account. If those settings could be saved in a sqlite3 file for example each "user" could use the same settings :) 

This could be a well appreciated feature

**Comment by fmarzocca** [comment]
It's not a good idea (IMHO), because each user has to set its proper username so that you  know who is playing (see screenshot). In addition, spotify settings (and other) are saved in mopidy.conf in the server. The settings you see in the browser's settings page are allowing the user to handle Spotify's libraries directly and this is something you don't want for any user opening a new browser. However for security reasons 'new' clients (browser) will not be pre-populated with a user's Spotify Authentication.
This is just a "one time" operation your users have to do on their browser, I don't see a big problem here.

![Schermata 2020-02-09 alle 17 17 04](https://user-images.githubusercontent.com/8530030/74105650-015c6f00-4b60-11ea-869f-d454809e9b0b.png)

**Comment by jaedb** [comment]
@moloni-pt the current method to share config between users is to (once connected) push your config from one client (user) to another. You can do this from _Settings > Share configuration_.
On another note, you once could share a link with pre-populated `host` and `port` values (eg `.../iris?host=192.168.1.1&port=6680`) however this seems to no longer be working. Would getting this working again achieve your use case?

**Comment by jaedb** [comment]
Further to this, it would create a security flaw in that anyone who connects to Iris would gain access to any authorized application keys (eg Spotify, LastFM, Genius). These are currently stored client-side in each user's browser.
By using the _Share configuration_ feature described above, this ensures that the sharing of credentials is more controlled and only triggerable by the authorized persons.

**Comment by jaedb** [comment]
I'm closing this issue as building this functionality introduces security and trust concerns for end users, which is not a path I would like to take Iris. It would also be a violation of the terms of use for third-party integrations (ie Spotify, LastFM, Genius, etc).
