### ISSUE TITLE
Error connecting with spotify - UNABLE_TO_CONTACT_SERVER: 8

### ISSUE THREAD

**Issue by nunong21** [jaedb/Iris#505]
Hello, 

I had mopidy-spotify playing without problems, and yesterday the music stopped. 
I went to Mopidy-Iris and now every time I try to play some music I get the error message saying "Mopidy: Failed to add some tracks". 

Since then I tried already doing multiple things, I checked my subscription (its a family plan with a valid subscription) and updated the credit card that was expiring at the end of this month. 

Generated full new tokens, client secrets, etc (even tried with a new login). 

And in my mopidy journal, I'm getting the messages: 

`Feb 26 10:24:01 mopidy[1119]: ERROR    [SpotifyEventLoop] spotify.session Spotify login error: <ErrorType.UNABLE_TO_CONTACT_SERVER: 8>
Feb 26 10:24:06 mopidy[1119]: INFO     [SpotifyBackend-6] mopidy_spotify.lookup Failed to lookup 'spotify:track:4RbKBuzAMn0e3dNpxH5Fql': Session must be logged in and online to load objects: <ConnectionState.LOGGED_OUT: 0>
`

After some googling what I found was related to the subscription (which I check and seems fine), and with the connected Facebook, which my account isn't connected to any Facebook. 

Has anyone had this problem solved?

**Comment by sorvakko** [comment]
Just piping in to confirm this issue. Kind of seems like Spotify might have shut down the libspotify API.

**Comment by jaedb** [comment]
This is a Mopidy-Spotify issue, rather than an Iris issue. The best place to raise this issue is on the [Mopidy-Spotify repo](https://github.com/mopidy/mopidy-spotify/issues), and I can see that other users are reporting similar behavior [#163](https://github.com/mopidy/mopidy-spotify/issues/163).

Curiously I had this issue at work (running on Mac OSX) but not at home (running on Docker). Same account and credentials.

**Comment by jaedb** [comment]
For updates, please refer to the [Mopidy-Spotify issue #257](https://github.com/mopidy/mopidy-spotify/issues/257).
