### ISSUE TITLE
New button to Shuffle Queue order (separate to Random Mode)

### ISSUE THREAD

**Issue by daverck** [jaedb/Iris#522]
Songs are played in shuffle but the list in "now playing" tab is not shuffled accordingly.

**To Reproduce**
Steps to reproduce the current behavior:
Go to (my) "tracks" tab
Click "Play all"
Click Shuffle icon
Compare playlist track order with the queue order and they're the same

**Describe the solution you'd like**
It would be nice if the list of songs in "now playing" was in the exact order they are played.

**Additional context**
related issues : #391 #304

**Comment by jaedb** [comment]
I think the confusion you're experiencing is because there are two different Mopidy functions:
1. [Random mode](https://docs.mopidy.com/en/latest/api/core/#mopidy.core.TracklistController.set_random)
2. [Shuffle queue](https://docs.mopidy.com/en/latest/api/core/#mopidy.core.TracklistController.shuffle)

Iris' shuffle icon toggles _Random mode_, meaning that the queue will play in a random order. Currently there is no Iris implementation of _Shuffle queue_ action, but I'm beginning to think it might make more sense.

So I can better understand your use case, what context would you be in when shuffling the queue? Would it be during the adding of tracks (like a playlist's _Shuffle play_ context menu option), or as a button in the _Now Playing_ section?

**Comment by daverck** [comment]
I think both the existing "Shuffle" icon and the context menu option for playlist ("Shuffle play") would be better using an implementation of the mopidy function "shuffle queue".
