### ISSUE TITLE
Unable to coexist with raspotify: Mopidy claims ALSA device.

### ISSUE THREAD

**Issue by Borromini** [jaedb/Iris#529]
**Describe the bug**
I used Mopidy with Moped before Mopidy bumped to 3.x; because Raspotify gave us better results with, we used Mopidy/Moped just for web radio and Raspotify for Spotify. They ran both alongside and that worked fine.

Now with having switched to Mopidy 3 and Iris (for web radio only still), we're seeing Raspotify break once we try to play anything through Spotify (through Raspotify).

Audio device is 0,0; at first I thought I had to specify it through Raspotify's settings but that doesn't make any difference (it worked wonderfully without before the Mopidy/Iris switch as well).

**To Reproduce**
1. Start the Raspotify service.
2. Start the Mopidy service with the Iris extension.
3. Play some music from Spotify through Raspotify (the Spotify app on your smartphone will see it the device running Raspotify as a Spotify device - apologies if terminology is off). Raspotify log will show this, e.g.:
```
Apr 25 21:47:58 rpi1 librespot[3757]: [2020-04-25T19:47:58Z INFO  librespot_playback::player] Loading <Somebody to Love Me> with Spotify URI <spotify:track:2Tky1eOpdLXo8yYawnTMcj>
Apr 25 21:47:59 rpi1 librespot[3757]: [2020-04-25T19:47:59Z INFO  librespot_playback::player] <Somebody to Love Me> loaded
```
4. Pause your Spotify track.
5. Play some radio stream through the Iris web interface, then pause it.
6. Try playing another track on your Spotify app; it looks like it's working but there's no sound, and Raspotify throws these errors:

```
Apr 25 21:47:59 rpi1 librespot[3757]: [2020-04-25T19:47:59Z ERROR librespot_playback::audio_backend::alsa] Alsa error PCM open ALSA function 'snd_pcm_open' failed with error 'EBUSY: Device or resource busy'
Apr 25 21:47:59 rpi1 librespot[3757]: [2020-04-25T19:47:59Z ERROR librespot_playback::player] Could not start audio: Alsa error: PCM open failed
```

**Expected behavior**
Coexistence between Raspotify and Mopidy/Iris

**Environment details:**
 - OS: Raspbian Buster, up to date.
 - Browser: Firefox (probably not relevant)
 - Mopidy / Iris version:
```
# pip3 list|grep Mopidy
Mopidy         3.0.2    
Mopidy-Iris    3.47.0   
Mopidy-Spotify 4.0.1    
Mopidy-TuneIn  1.0.0
```

It's a long shot, but maybe having a stop button (like https://github.com/jaedb/Iris/issues/434) might fix this? Maybe Mopidy is still keeping the ALSA device active because the stream is paused, not stopped?

**Comment by jaedb** [comment]
Firstly, thanks for the thorough issue report!

The quick way to test if pause is what is causing the issue would be stop Mopidy playback. You can do this in Iris by going to _Settings > Debug > Mopidy_ and enter `playback.stop` in the _Call_ field. Then try and play from Raspotify and let me know how that goes.

Failing that, it's likely to be a Mopidy issue, rather than an Iris issue.

**Comment by clavelc** [comment]
Hi,

I could reproduce the issue only once (on the Android Spotify app), otherwise it seems to work both from the Android app and from the linux Spotify app. Actually I can play two different songs simultaneously which is strange.. I tried playback.stop once but then couldn't reproduce it anymore to try again.

**Comment by jaedb** [comment]
@clavelc I'm a bit confused about the link between Android Spotify app and Iris. The two are two entirely separate systems, so I don't think it is related to the original issue. Unless I misunderstand your comment?

As a side-note, I have also noticed I can play Spotify from two devices at once which I couldn't previously do.

**Comment by kingosticks** [comment]
Pause does not release the ALSA device. That's intentional, it hasn't changed with the 3.x release and it's not a bug.

If you still have this issue you need to either issue a stop command when switching (librespot let's you run a command before it's playback starts, you can use that to run `mpc stop`), or, configure ALSA on your system to use a dmix plug, this let's multiple processes use the same output device at the same time i.e. Mopidy would be paused and silent but still have access to the device while Raspotify was playing.  There's lots of info online about how to configure ALSA's dmix plug.

**Comment by jaedb** [comment]
@Borromini as per @kingosticks comments above, this isn't something that I can fix within Iris. The workaround is to ensure you _stop_ your stream from Iris (keyboard shortcut `s`) to release ALSA.

**Comment by Borromini** [comment]
@jaedb Sorry about getting back to you on this so late. I've been buried in other stuff...

I tried using s but that pops up the search window.
