### ISSUE TITLE
API documentation

### ISSUE THREAD

**Issue by N-kay** [jaedb/Iris#559]
*What part of Iris is your question about?*
Iris API

**Your question**
Apparently Iris exposes its own API, see [here](https://github.com/jaedb/Iris/issues/430#issuecomment-526372061). This isn't documented at all.

This should really be in the project wiki. I would like to help with that. Can someone point me to the relevant section of the source code I can find out more about the API?

[Edit]
Turns out all methods from the [IrisCore](https://github.com/jaedb/Iris/blob/master/mopidy_iris/core.py) class are available through the API? That seems a little unsafe. Looking into it more.

**Comment by jaedb** [comment]
It is not documented because it is an internal API - not really intended for integration. These methods are required for the frontend to communicate with the Iris backend. I have exposed these methods via WS and HTTP so the frontend can use the protocol that is most appropriate (ie WS for most, HTTP for async or chained fetch requests).

I don't believe the methods exposed from IrisCore are unsafe, but if you feel otherwise, I am keen to hear your thinking. The thing to bear in mind is that this isn't really any different to the JSONRPC / WS API exposed by Mopidy itself.
