### ISSUE TITLE
Display stream title for Internet radio streams

### ISSUE THREAD

**Issue by maxerenberg** [jaedb/Iris#582]
**Describe the bug**
When an Internet radio stream (e.g. Shoutcast) is playing, the stream title is not displayed in the PlaybackControls or the "Now Playing" queue.

**To reproduce**
Add the URL of an Internet radio stream to a playlist, say ~/.local/share/mopidy/m3u/Radio.m3u8. In Iris, go to Playlists and begin playing the stream. The stream title does not appear.

**Expected behaviour**
The stream title of the currently playing song should appear.

**Environment details**
* OS: Ubuntu 20.04
* Browser: Firefox 79.0
* Iris version: 3.51

I've implemented a possible fix at [maxerenberg/Iris](https://github.com/maxerenberg/Iris). I've attached screenshots below of before and after.

Before:
![image](https://user-images.githubusercontent.com/34190303/90303481-4c8f6b80-de7c-11ea-8f09-d90ffb8d049e.png)

After:
![image](https://user-images.githubusercontent.com/34190303/90303432-e9053e00-de7b-11ea-9152-b5dda2fdd5e9.png)

**Comment by jaedb** [comment]
I've had a quick look through your commits, and it looks great. Please open a PR with your finalised changes and we can take it from there.

One thing I did think about your approach is that we don't need to involve the Pusher websocket, nor add the backend listener. Mopidy broadcasts the [`stream_title_changed`](https://docs.mopidy.com/en/latest/api/core/#mopidy.core.CoreListener.stream_title_changed) event to the Mopidy websocket (just like `current_track_changed`) so we can lean on that rather than using Pusher.

**Comment by maxerenberg** [comment]
Good idea. I replaced the Pusher with the Mopidy event in my PR.

**Comment by jaedb** [comment]
Released in `3.54.2`
