### ISSUE TITLE
Is there an option to change the default system PORT variable?

### ISSUE THREAD

**Issue by shaunmulligan** [jaedb/Iris#70]
Currently I have a raspberry pi serving Iris via a ngrok tunnel. This works well, but I always have to first change the default `PORT` on the settings page from 6680 to 80 before things get going. Is there a way to have that default to port 80

**Comment by onekreg** [comment]
Mopidy isn't able to work on port 80. Therefore you have use port forwarding with iptables.

**Comment by jaedb** [comment]
In order to run Mopidy via port 80, you could try using a proper webserver (eg Apache) to host the static files. 

Clone this repository into your /var/www/ directory and run a build (eg `npm install && npm run dev && npm run prod`). Then you can access the Iris frontend it on whatever port you wish.

This is a limitation of Mopidy, rather than Iris.

**Comment by DaEkstrim** [comment]
I got around this by modifying the javascript being returned by the nginx reverse proxy using the subs filter module.

                subs_filter_types application/javascript text/javascript;
                subs_filter 'port:6680' 'port:80';

Since the javascript file is minified, there is only one, hence the extra load on nginx during the website load time is negligible. Worked like a charm.

Disclaimer: This is NOT future proof. If they change the variable name, assignment method or anything related to how the settings are stored, this will no longer work.
