### ISSUE TITLE
Choppy / stutter snapcast playback when using Iris as snapcast client.

### ISSUE THREAD

**Issue by MrSurly** [jaedb/Iris#707]
**Describe the bug**
Snapcast playback in choppy when using Iris

**To Reproduce**
1. Setup Mopidy, Iris, and a snapcast server
2. Enable streaming to Iris via snapcast
3. Play music
4. Do a search or other navigation
5. Stutterning audio

**Expected behavior**
Clear audio

**Console log**
```
Searching for all matching "led zeppelin"
```

**Environment details:**
 - OS: Ubuntu Desktop 21.04
 - Browser: Firefox 85.0.1 (64-bit)
 - Iris version: 3.55.4

**Additional context**
* snapclient on the same machine as the Iris instance does not have a problem.

**Comment by jaedb** [comment]
Unfortunately I can't see a clear path to directly resolve this.
I am currently working on performance improvements which should reduce the likelihood of this, but if your browser is under load then stutters will happen. This is especially noticeable when the browser is in background due to how they downgrade CPU priority.
This is the downside to running audio streaming via the javascript thread, within a browser.
