### ISSUE TITLE
First item of "now playing" playlist is never shuffled

### ISSUE THREAD

**Issue by svenb1234** [jaedb/Iris#724]
**Describe the bug**
The first item of the "now playing" playlist is not shuffled.

**To Reproduce**
1. Set a playlist to play -> songs are put into the "now playing" playlist
2. Change to the "now playing" tab and click on "Shuffle" on the right of the album cover.
3. The first item in the playlist never changes to another position. (at least not after clicking 20+ times on "shuffle")

**Expected behavior**
All songs should be shuffled.

3.57.3

**Comment by jaedb** [comment]
This is intentional. The logic is that if the current track is the first in the queue, then it will remain so. The reason for this is that the tracks will play sequentially from the current track. Anything above the current track will never be played.

_Shuffle_ in Iris is designed as a one-time shuffle of the current tracks; if you want to to play _Random_ then use the _Random_ toggle in the play bar.
