### ISSUE TITLE
Set volume with android smartphone hardware buttons

### ISSUE THREAD

**Issue by svenb1234** [jaedb/Iris#727]
**Is your feature request related to a problem? Please describe.**
Iris does not react to the hardware volume buttons on my Pixel 4a. Thus I always have to unlock the phone in order to set the volume.

**Describe the solution you'd like**
As with the Chromecast media session, I would like Iris to react to the hardware buttons when its media session is started and visible on the lock screen.

Also, it would be very handy to see the iris media session volume as separate volume slider in the Android UI, i.e. when pressing the volume buttons while the screen is unlocked, as it is the case for Chromecast - if that is possible.

**Comment by bluepuma77** [comment]
I think you should add "smartphone" to the title. I use Mopidy+Iris on Raspberry Pi, there hardware buttons work fine :-)

**Comment by svenb1234** [comment]
Thanks for the hint!

**Comment by jaedb** [comment]
Iris uses `MediaSession` which most browsers support (see [MediaSession spec](https://w3c.github.io/mediasession/#the-mediasession-interface) for available actions). Volume control is not available to this interface so unfortunately this is not possible without a dedicated Android app.

Volume controls _are_ available from a desktop however, so that's why it works well on Rpi :-)

By comparison Chromecast is a native Android app, so has access to media volume controls.
