### ISSUE TITLE
Does the built-in snapcast client support Opus codec?

### ISSUE THREAD

**Issue by tilllt** [jaedb/Iris#728]
I configured my snapcast server to transmit the streams compressed with the "opus" codec. Both Chrome and Firefox have built-in Opus codec support. Still, when activating the snapcast server in Mopidy-Iris a modal box pops up  saying "Codec not supported: opus". Is this a configuration mistake on my side or does the client indeed not support the opus codec?

Bonus question: is this error message referring to that lack of opus support in the browser or in the snapweb client?

**Comment by kingosticks** [comment]
Iris includes a copy (?) of snapweb, including a copy of its missing support for Opus. See https://github.com/badaix/snapweb/issues/8

**Comment by tilllt** [comment]
It's especially unfortunate since the ESP32 snapclients implementation ONLY compressed option is opus (or PCM)

**Comment by tilllt** [comment]
And another question, sorry if thats obvious: why does snapweb needs to have its own OPUS implementation and cannot use the browsers built-in opus codec?

**Comment by kingosticks** [comment]
Because it (along with all of snapcast) is designed to provide  synchronised playback across multiple clients. To do that requires a more complicated playback algorithm. The regular playback in the browser cannot do that. It doesn't matter if you are not using the synchronisation feature, that's how it works.

**Comment by jaedb** [comment]
This is really a question for the [Snapweb author](https://github.com/badaix/snapweb) because the Iris implementation is derivative of that. Quite literally, `src/js/components/SnapStream.tsx` comes from the Snapweb project.

FWIW: you are also more likely to get useful answers by posting __questions__ like this on the [Discourse forum](https://discourse.mopidy.com/), rather than the Iris issue tracker.

**Comment by jaedb** [comment]
What @kingosticks said ☝️ 
I am relatively fresh when it comes to understanding the inner workings of audio streaming.

**Comment by tilllt** [comment]
> Because it (along with all of snapcast) is designed to provide synchronised playback across multiple clients. To do that requires a more complicated playback algorithm. The regular playback in the browser cannot do that. It doesn't matter if you are not using the synchronisation feature, that's how it works.

Sure. But as it is stated in the README of Snapcast, it does achieve sync but dropping single samples to speed up playback, so in theory this could be done before or after the stream is transported with build-uin (or HW implemented) codecs, like opus?

**Comment by kingosticks** [comment]
I don't believe the browser audio API provides any mechanism to do that but if you have an implementation please discuss/provide it at https://github.com/badaix/snapweb/issues/8

**Comment by tilllt** [comment]
I will take the issue to Snapweb, but this sure sounds as if it was possible to adapt playback speed:
https://developer.mozilla.org/en-US/docs/Web/API/AudioBufferSourceNode/playbackRate
