### ISSUE TITLE
Progressive Web App

### ISSUE THREAD

**Issue by hughwilliams94** [jaedb/Iris#773]
**Describe the solution you'd like**
Iris looks and works great on mobile, but it would be great to have a PWA that one could install to the home screen. It might also speed up load times?

**Describe alternatives you've considered**
Running the web app in normal browser works fine but it would be great to have a little tighter integration

**Comment by jaedb** [comment]
The great news is that Iris already is a PWA. In order to enjoy progressive web applications, they need to be running over SSL (or `localhost`).
You'll need to have an understanding of setting up a proxy to achieve this, and the implementation instructions for Iris can be found in the [Iris Wiki](https://github.com/jaedb/Iris/wiki/Advanced#encryption-httpswss).
