### ISSUE TITLE
Mopidiy-Iris docker can not play internet radio

### ISSUE THREAD

**Issue by zsamiatt** [jaedb/Iris#784]
I would like listen internet radio stream. It worked earlier. 

XXX.m3u files:
#EXTM3U
#EXTINF:-1,Radio1
link (I tested the link in VLC and the link is good)

I see this in docker log:

WARNING  2021-11-03 16:46:30,269 [8:MainThread] mopidy.audio.actor
  Could not find a text/uri-list decoder to handle media.
WARNING  2021-11-03 16:46:30,301 [8:MainThread] mopidy.audio.gst
  GStreamer warning: No decoder available for type 'text/uri-list'.
ERROR    2021-11-03 16:46:30,301 [8:MainThread] mopidy.audio.gst
  GStreamer error: Your GStreamer installation is missing a plug-in.
WARNING  2021-11-03 16:46:30,518 [8:MainThread] mopidy.audio.actor
  Could not find a text/uri-list decoder to handle media.
WARNING  2021-11-03 16:46:30,521 [8:MainThread] mopidy.audio.gst
  GStreamer warning: No decoder available for type 'text/uri-list'.
ERROR    2021-11-03 16:46:30,524 [8:MainThread] mopidy.audio.gst
  GStreamer error: Your GStreamer installation is missing a plug-in.
WARNING  2021-11-03 16:46:39,950 [8:MainThread] mopidy.audio.actor
  Could not find a text/uri-list decoder to handle media.
WARNING  2021-11-03 16:46:39,951 [8:MainThread] mopidy.audio.gst
  GStreamer warning: No decoder available for type 'text/uri-list'.
ERROR    2021-11-03 16:46:39,951 [8:MainThread] mopidy.audio.gst
  GStreamer error: Your GStreamer installation is missing a plug-in.

**Comment by jaedb** [comment]
`Could not find a text/uri-list decoder to handle media.` means that you are missing an extension to handle that URI type. Perhaps you recently uninstalled an extension?

This doesn't relate to Iris itself, rather the configuration of your backend extensions. The best place to find an answer to this kind of issue is on the [Mopidy Discourse](https://discourse.mopidy.com/) forum.

**Comment by zsamiatt** [comment]
"Perhaps you recently uninstalled an extension?"
No. This is your docker file. I dont know how can installing/uninstalling in docker file!

**Comment by jaedb** [comment]
This is the very reason I created issue templates - so that all of the information necessary to resolve issues is provided. You opted to ignore this template.

You also mention "It worked earlier.". Please provide more information about that. What has changed with your environment since "it worked"?

What version of [Iris Docker image](https://hub.docker.com/r/jaedb/iris) are you using now, and were you using "when it worked"? You can also get the source version by running this command (you may need to change the container name if you've customised this):
```
docker exec -u root -it iris_mopidy_1 bash -c cd /iris &&  git describe --tag
```

This may seem like I'm giving you homework, but providing a good quality bug report is the best thing users can do to help get issues fixed. It also means I can spend more time making Iris better, rather than blindly debugging.

**Comment by zsamiatt** [comment]
Before I started using docker, I used the mopidy, iris and snapcast in debian VM. In the meantime, I deleted the VM.
I using latest amd64 docker which appeared "Last pushed24 days agobyjaedb". 

If I try runing this command the NAS said -ash: git: command not found.

sorry for the incomplete information!

**Comment by jaedb** [comment]
Docker containers are insulated from your host system. In your case it sounds like you're running Docker on a NAS. Anything you may have installed on your NAS is not* available within your container. So because it worked on your NAS does not mean it'll work within Docker. You will need to have the also software installed in the Iris Docker container for this to work.

What _exactly_ is the internet radio software you're using? Is there a Mopidy extension that you use to support these URI types? The error `GStreamer warning: No decoder available for type 'text/uri-list'.` as mentioned previously, indicates you're missing this Mopidy extension.

This really sounds like a deeper issue with your setup, not something directly related to Iris. It also would appear it doesn't have anything to do with a recent Iris release (ie a regression issue). For this reason, I am directing you to the [Mopidy Discourse](https://discourse.mopidy.com/). I recommend you provide a thorough explanation of the software you use to support your radio functionality, as well as your Docker environment details. Hopefully you can find your answer there.

(*) my understanding of containers is far from expert, but you can generally assume guest (container) and host (NAS) are entirely separate machines.

**Comment by zsamiatt** [comment]
Hello, The internet radio is only the url stream not a software. Previously I play the stream with mopidy.
