### ISSUE TITLE
Spotify UI, cant go to albums with a  /  in the name

### ISSUE THREAD

**Issue by fakeplastic** [jaedb/Iris#785]
When browsing my albums in the spotify UI, I cannot go to an album page that has a forward slash / in the name. It gives a "Oops that link could not be found" error.

**To Reproduce**
1. Add spotify to sources
2. search for an album with a slash in the name (such as the Spoon album "Breakdown / A Face In The Crowd (Live)"
3.  Click on the album, will get an error

**Comment by jaedb** [comment]
Please complete the **Environment details:** section of the issue template. This issue was fixed in a previous version of Iris, so I expect a simple upgrade should resolve this issue for you.

---

**Environment details:**
 - OS: [e.g. iOS]
 - Browser [e.g. chrome, safari]
 - Iris version [e.g. 3.54.0]

**Comment by fakeplastic** [comment]
Yes, I was on an older version. An update fixed it. Thank you
