### ISSUE TITLE
Release radar and Discover weekly playlists can't be played as a whole playlist

### ISSUE THREAD

**Issue by vojtapolasek** [jaedb/Iris#79]
Hi,
Linux, Mopidy version 2.1.0, Iris version 2.13.1. I have premium Spotify account.
I managed to add Release radar and Discover weekly playlists to my library through my Smartphone and I can see them in Iris. I can see even songs in them and when I click individual songs, they play without problems.
But when I load them and click the "Play" button, I get "Unable to load URIs" after several tens of seconds.
Here is URI of my Discover weekly playlist:
spotify:user:spotify:playlist:37i9dQZEVXcTCkqZyORAc7
Can I provide some more info?

**Comment by eltufto** [comment]
Having the same issue.  Just installed mopidy + iris on raspberry pi 3.  Cannot play any playlist as a whole, always gives error "Unable to load URIs".

Individual songs can be played though.

**Comment by jaedb** [comment]
See #36

**Comment by vojtapolasek** [comment]
Well, but Release radar and Discover weekly have only 30 songs each. And
I set timeout for mopidy-spotify to 60. So is this a problem with
Spotify API?

**Comment by eltufto** [comment]
the playlist I'm attempting to play has only 8 songs.

**Comment by eltufto** [comment]
Also similarly wondering if it's an issue with mopidy-spotify.

When I browse with ncmpcpp no playlists even show up. It's only through
Iris that they are visible. Playlists are discovered via a different
mechanism in Iris?  Spotipy?

On Mar 6, 2017 11:22 PM, "Stephen Tufts" <stephen.tufts@gmail.com> wrote:

 the playlist I'm attempting to play has only 8 songs.

**Comment by jaedb** [comment]
When Iris produces the error _Unable to load URIs_, indicates our URI lookup via Mopidy and we get an empty response. There is some assumption here, but generally an empty response means Mopidy was unable to load said URI(s). This could be for any number of reasons, including timeouts, invalid URIs or no matches.

I would suggest attempting to load your URI via another Mopidy client (I recommend [ncmpcpp](https://docs.mopidy.com/en/latest/clients/mpd/#ncmpcpp) for testing) to see if this issue runs deeper than Iris.

As a side-note, it could be due to Spotify performing maintenance on their servers, causing them to run slowly or not respond at all.

**Comment by vojtapolasek** [comment]
Hi,
that's the strange thing. I use Gmpc instead of ncmpcpp but this
shouldn't matter. I can see all my Spotify playlists in root of my music
database, but except for Release radar and Discover weekly. They aren't
there. But Iris can see them and display their songs. These songs can be
even played individually. How does Iris get to those playlists?

**Comment by jaedb** [comment]
Iris gets playlists via two methods: Mopidy's [`playlists.asList`](https://docs.mopidy.com/en/latest/api/core/#mopidy.core.PlaylistsController.as_list) and Spotify's [Get User's Playlists](https://developer.spotify.com/web-api/get-list-users-playlists/)

**Comment by jaedb** [comment]
Closing as the issue (playing large playlists) will be addressed in #36
