### ISSUE TITLE
Add support to Owntone MPD server implementation

### ISSUE THREAD

**Issue by chourmovs** [jaedb/Iris#910]
### Problem to solve
Hi, I've [owntone](url) running on my primo tinkerboard on debian buster, I've also mopidy setup with your pretty frontend, I can't connect it to owtone MPD, my goal was to have one to rule them all

![image](https://github.com/jaedb/Iris/assets/40670708/96a86b5d-bdf0-46c7-92d8-44822649b944)
![image](https://github.com/jaedb/Iris/assets/40670708/9805cad8-6ec9-43e0-adc5-55dab6da08e7)

### Proposed solution

Please can you have a look at what should be done to make this possible

### Additional info

where to start : https://owntone.github.io/owntone-server/

Known limitations : https://owntone.github.io/owntone-server/clients/mpd/

**Comment by jaedb** [comment]
Unfortunately I don't see this as being possible.

Mopidy is _based_ upon MPD but they're not the same thing. While Iris is indeed a frontend for Mopidy, it has backend components as well. As such, Iris is intended to be run on Mopidy, not MPD.

The errors you are seeing are likely due to Iris making requests to the backend which don't exist (the Iris backend is not running on your MPD server).
